type DefaultPublicMemoryItem = {
  id: string;
  scope: 'public';
  kind: 'manual';
  status: 'active';
  source: 'manual';
  stageId: string;
  title: string;
  text: string;
  sourceReferences: [];
  createdAt: number;
  updatedAt: number;
};

type DefaultPublicMemoryDefinition = {
  title: string;
  text: string;
};

type DefaultCoursePublicMemoryInput = {
  id: string;
  name?: string | null;
  courseCode?: string | null;
  tags?: readonly string[] | null;
};

const MAT136_PUBLIC_MEMORY_UPDATED_AT = Date.parse('2026-05-20T00:00:00.000Z');
const MAT102_PUBLIC_MEMORY_UPDATED_AT = Date.parse('2026-06-02T00:00:00.000Z');

const mat136CoursePublicMemory: DefaultPublicMemoryDefinition = {
  title: 'MAT136 课程知识地图',
  text: [
    '## 课程知道的知识点',
    '- Riemann sum：用分割、采样点和矩形面积和近似曲线下方面积。',
    '- Riemann integrability：当 mesh 变细且所有合法采样方式趋向同一个极限时，函数可黎曼积分。',
    '- Definite integral：把黎曼和极限、有向面积和净变化统一到定积分符号中。',
    '- FTC II：用反导函数计算定积分，核心形式是 F(b) - F(a)。',
    '- FTC I：面积函数和变上限积分的求导，遇到复合上限时要乘以上限导数。',
    '- u-substitution：把复合函数积分看成反向链式法则，处理变量、du、上下限和回代。',
    '- inverse / trig substitution：针对 sqrt(a^2 - x^2)、sqrt(a^2 + x^2)、sqrt(x^2 - a^2) 选择 sin、tan、sec 代换。',
    '- integration by parts：把乘积法则反过来使用，按 u、dv、du、v 管理剩余积分。',
    '- area and volume applications：用 slicing、washer、shell 等方式把几何量写成积分。',
    '',
    '## 讲解重点',
    '- 课程主线不是单个公式堆叠，而是“面积近似 -> 极限定义 -> 计算工具 -> 换元/分部技巧 -> 应用建模”。',
    '- 每节笔记本都要先讲它解决什么问题，再讲公式；例如换元法解决复合函数，分部积分解决乘积结构。',
    '- 反复训练学生从题目结构判断方法：是 Riemann sum 翻译、FTC 计算、u-sub、trig-sub，还是 integration by parts。',
    '- 对定积分题要同时检查符号、上下限、几何含义和代数计算，避免只把积分当作机械反导。',
    '- 对应用题强调建模步骤：画变量、写截面积或壳体表达式、确定 bounds，再积分。',
    '',
    '## 笔记本覆盖关系',
    '| 笔记本 | 覆盖知识点 | 讲解重点 |',
    '| --- | --- | --- |',
    '| 黎曼积分 | partition、sample point、Riemann sum、mesh、integrability | 从矩形近似面积走到可积定义 |',
    '| 定积分 | signed area、properties、FTC II、Riemann sum conversion、FTC I | 把面积、极限和反导计算接起来 |',
    '| 换元法 | u、du、变量替换、定积分上下限 | 识别内层函数和外层导数影子 |',
    '| 逆换元法 | 三角代换、配方、回代、定义域 | 用形状选择 sin / tan / sec |',
    '| 分部积分 | u dv、du、v、多次分部、ln x、反三角函数 | 选择 u 和 dv，让剩余积分更简单 |',
    '| 面积与体积 | slicing、washer、shell、几何积分 | 先建模，再计算积分 |',
  ].join('\n'),
};

const mat136PublicMemories: Record<string, DefaultPublicMemoryDefinition> = {
  'nb-mat136-riemann-integral-week1-20260518135718': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- 黎曼积分从矩形近似面积出发，把分割、采样点和面积求和统一起来。',
      '- 分割 P、采样点 c_i、子区间宽度 Δx_i 与求和表达式 Σ f(c_i)Δx_i。',
      '- 左端点、右端点、中点等常见采样规则。',
      '- 单调函数下左/右黎曼和的高估和低估关系。',
      '- mesh 趋近 0 时，黎曼和极限若不依赖采样点，就定义为黎曼积分。',
      '',
      '## 讲解重点',
      '- 按“分割区间、选采样点、加矩形面积、取极限”的流程讲清黎曼积分。',
      '- 区分某一次黎曼和近似值与真正的定积分极限。',
      '- 强调采样点可以变，但可积函数在分割变细时会收敛到同一个面积。',
      '- 用图像和表格例题训练学生把文字条件翻译成求和式。',
    ].join('\n'),
  },
  'nb-mat136-definite-integral-week1-20260518150500': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- 定积分作为黎曼和极限，也可以表示有向面积和净变化。',
      '- 有向面积的正负号、积分上下限方向和区间可加性。',
      '- 定积分基本性质：线性、常数倍、区间拆分和比较直觉。',
      '- 微积分基本定理第二部分：用反导函数计算定积分。',
      '- 黎曼和与定积分符号之间的互相转换。',
      '- 微积分基本定理第一部分、面积函数、变上限积分和链式法则。',
      '',
      '## 讲解重点',
      '- 把定积分同时讲成三种面孔：面积、极限、反导计算工具。',
      '- 先建立符号和几何意义，再进入 FTC 的计算捷径。',
      '- 重点训练从 Riemann sum 极限识别积分区间、被积函数和 dx。',
      '- 对变上限积分强调“先求导外层面积函数，再乘以上限导数”。',
    ].join('\n'),
  },
  'nb-mat136-substitution-week2-20260518183518': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- 换元法是反向链式法则，用 u 把复合函数积分化简。',
      '- 选择 u、计算 du，并处理差一个常数或负号的情况。',
      '- 换元后不能留下原变量 x，需要把所有部分都改写成 u。',
      '- 定积分换元时，上下限也要随变量一起改变。',
      '- 函数缩放型换元和没有现成公式时的结构识别。',
      '',
      '## 讲解重点',
      '- 每道题都按四个问题讲：u 选什么、du 是什么、是否还有 x、上下限怎么办。',
      '- 用例题集中处理常数倍、负号和残留变量这些最常见错误。',
      '- 对不定积分强调最后换回 x；对定积分强调换上下限后可以不换回。',
      '- 让学生先找“里面的函数”和“外面的导数影子”，再动手计算。',
    ].join('\n'),
  },
  'nb-mat136-inverse-substitution-week2-v2-20260519174000': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- 普通 u-substitution 在根号二次式中为什么会卡住。',
      '- 三角代换把根号形状转成三角恒等式可以处理的结构。',
      '- 三类根号形状和代换规则：a^2 - x^2、a^2 + x^2、x^2 - a^2。',
      '- 配方后识别形状、换上下限、回代和定义域检查。',
      '- sin、tan、sec 代换背后的几何直觉。',
      '',
      '## 讲解重点',
      '- 先讲“为什么需要逆换元”，再给代换表，避免学生机械套公式。',
      '- 把根号形状和单位圆/直角三角形图像绑定起来。',
      '- 对每类代换都强调它消掉根号的那一步恒等式。',
      '- 用多个例题展示从诊断形状到完成积分的稳定流程。',
    ].join('\n'),
  },
  'nb-mat136-integration-by-parts-week2-v2-20260519151624': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- 分部积分作为乘积法则的积分版：∫ u dv = uv - ∫ v du。',
      '- 选择 u 和 dv 的原则：u 求导变简单，dv 可以直接积分。',
      '- 典型题型：x cos x、ln x、需要多次分部的积分。',
      '- 进阶题型：先换元再分部的 ∫ x^3 cos(x^2) dx，以及反三角函数 ∫ arctan x dx。',
      '- 公式推导、角色表、剩余积分的难度判断。',
      '- 一次分部不够时，重复使用分部积分并整理结果。',
      '',
      '## 讲解重点',
      '- 用“为什么换元不够”引出分部积分，再从乘积法则推导公式。',
      '- 每题先做角色选择，不急着计算，训练学生解释为什么这样选。',
      '- 对 ln x 强调把它看成 ln x · 1，并令 dv = dx。',
      '- 对重复分部题强调过程管理：每一步都要让剩余积分更可控。',
      '- 对 PDF 补充例题强调先判断结构：能先消内层就先换元，剩下乘积再分部。',
    ].join('\n'),
  },
};

const cpsc107PublicMemories: Record<string, DefaultPublicMemoryDefinition> = {
  'nb-cpsc107-racket-basics-week1-20260519024537': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- Racket 的基本阅读方式：一切都是表达式，表达式会被求值为 value。',
      '- 前缀表达式、operator / operands、primitive operators 和 built-in functions。',
      '- 求值规则：从左到右、从里到外，每一步只化简一个表达式。',
      '- Boolean 值、and / or / not 规则，以及短路求值。',
      '- String、Image、Number、Boolean 等 primitive data 的类型区别和常见操作。',
      '- 函数定义、函数调用求值、参数绑定、global constants、if 和 cond。',
      '',
      '## 讲解重点',
      '- 训练学生读代码时先问：这个表达式的 operator 是什么，operands 是什么，最后会得到什么值。',
      '- 用逐步化简展示 Racket 的求值顺序，尤其强调短路求值和分支只执行其中一路。',
      '- 反复区分不同 primitive data 类型，避免把 String、Number、Image 混用。',
      '- 把数学函数翻译成 Racket 函数时，强调参数只是占位符，调用时才用实际值替换。',
      '- 对 if / cond 重点讲清判断顺序、分支选择和没有被选中的分支不会求值。',
      '',
      '## Racket 代码参考',
      '```racket',
      ';; prefix notation: operator first, operands after',
      '(check-expect (+ (* 2 3) (- 10 4)) 12)',
      '',
      '(define TAX-RATE 0.13)',
      '(define PASS-LINE 50)',
      '(define HONOURS-LINE 85)',
      '(define MAX-MISSED 2)',
      '',
      '(@signature Number -> Number)',
      ';; produce total price after tax',
      '(check-expect (total 100) 113)',
      ';(define (total price) 0) ;stub',
      '',
      '(@template-origin Number)',
      '(@template',
      ' (define (total price)',
      '   (... price)))',
      '',
      '(define (total price)',
      '  (* price (+ 1 TAX-RATE)))',
      '',
      '(@signature Number -> String)',
      ';; produce "negative", "zero", or "positive" for n',
      '(check-expect (sign -2) "negative")',
      '(check-expect (sign 0) "zero")',
      '(check-expect (sign 3) "positive")',
      ';(define (sign n) "zero") ;stub',
      '',
      '(@template-origin Number)',
      '(@template',
      ' (define (sign n)',
      '   (... n)))',
      '',
      '(define (sign n)',
      '  (cond [(< n 0) "negative"]',
      '        [(= n 0) "zero"]',
      '        [else "positive"]))',
      '',
      '(@signature Number Number Boolean -> String)',
      ';; produce final standing from grade, missed labs, and project status',
      '(check-expect (standing 92 0 true) "honours")',
      '(check-expect (standing 92 3 true) "incomplete")',
      '(check-expect (standing 48 0 true) "fail")',
      '(check-expect (standing 92 0 false) "incomplete")',
      ';(define (standing grade missed project-submitted?) "fail") ;stub',
      '',
      '(@template-origin Number Number Boolean)',
      '(@template',
      ' (define (standing grade missed project-submitted?)',
      '   (... grade missed project-submitted?)))',
      '',
      '(define (standing grade missed project-submitted?)',
      '  (cond [(or (not project-submitted?)',
      '             (> missed MAX-MISSED))',
      '         "incomplete"]',
      '        [(and (>= grade HONOURS-LINE)',
      '              (<= missed 1))',
      '         "honours"]',
      '        [(>= grade PASS-LINE) "pass"]',
      '        [else "fail"]))',
      '',
      ';; Stepper trace: MAX-MISSED is used when first OR question is false.',
      ';; (standing 92 3 true)',
      ';; => (cond [(or (not true)',
      ';;               (> 3 MAX-MISSED))',
      ';;           "incomplete"]',
      ';;          [(and (>= 92 HONOURS-LINE)',
      ';;                (<= 3 1))',
      ';;           "honours"]',
      ';;          [(>= 92 PASS-LINE) "pass"]',
      ';;          [else "fail"])',
      ';; => (cond [(or false (> 3 2))',
      ';;           "incomplete"]',
      ';;          ...)',
      ';; => (cond [(or false true)',
      ';;           "incomplete"]',
      ';;          ...)',
      ';; => (cond [true',
      ';;           "incomplete"]',
      ';;          ...)',
      ';; => "incomplete"',
      '',
      ';; Stepper trace: if first OR question is true, second is skipped.',
      ';; (standing 92 0 false)',
      ';; => (cond [(or (not false)',
      ';;               (> 0 MAX-MISSED))',
      ';;           "incomplete"]',
      ';;          ...)',
      ';; => (cond [(or true (> 0 MAX-MISSED))',
      ';;           "incomplete"]',
      ';;          ...)',
      ';; => "incomplete"',
      '```',
    ].join('\n'),
  },
  'nb-cpsc107-htdf-htdd-week2-20260519043417': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- HTDF 是设计函数的固定流程：function name、signature、purpose、examples、stub、template、function body。',
      '- Signature 声明函数 consume / produce 的数据类型，目前常见类型包括 Number、String、Boolean、Image，并可细分 Integer、Natural。',
      '- Purpose 必须一行内说明输入和输出，通常不超过 80 个字符；examples 用 check-expect 表达预期行为。',
      '- Stub 是带正确函数名、参数个数和返回类型的空壳函数；Number 返回 0，String 返回 ""，Image 返回 empty-image。',
      '- HTDD 用来设计数据，包括 @htdd、interp、examples、@dd-template-rules 和由数据形状推导出的 template。',
      '- Atomic non-distinct / atomic distinct 的区别：普通 Number/String/Boolean/Image/Interval 走 non-distinct，固定值如 "red"、false、empty 走 distinct。',
      '- 自定义数据类型可以用更有语义的名字，例如 CityName 比 String 更能说明函数真正接受什么。',
      '- One-of 包含 enumeration 和 itemization；enumeration 是有限固定值，itemization 是不同类型或形状的组合。',
      '- Compound data 用 define-struct 表示一个值同时拥有多个字段，并用 selector 取出字段。',
      '',
      '## 讲解重点',
      '- 先让学生填 HTDF 七步，再打开 Racket 写代码，避免直接跳到 body。',
      '- 用 circle-area 讲清 HTDF 的完整结构：signature、purpose、check-expect、stub、template、body 每一项都服务于函数实现。',
      '- 用 next-color 对比“裸代码”和“加 HTDF 后的代码”，说明 design record 能让函数意图和测试更容易读懂。',
      '- 对 stub 要强调只有一个分号，并且 dummy result 必须符合 signature 的输出类型。',
      '- 讲 HTDD 时反复把数据类型、template rule 和 template body 连起来，提醒学生 template 不是凭感觉写的。',
      '- 讲 enumeration 时强调 normal enumerations 不用 else；讲 itemization 时强调 cond question 要先用 type predicate guard，最后一问用 else。',
      '- 讲 compound data 时强调它不是 one-of：compound 的字段同时存在，selector 是 template 的核心。',
      '',
      '## PDF 表格整理',
      '',
      '### HTDF 七步',
      '| 顺序 | HTDF 部分 | 讲解记忆点 |',
      '| --- | --- | --- |',
      '| 1 | Function Name | 函数名要让人看出这个函数大概做什么。 |',
      '| 2 | Signature | 写出函数 consume 什么类型的数据、produce 什么类型的数据。 |',
      '| 3 | Purpose | 用一行说明函数输入和输出，不超过两句话，通常不超过 80 个字符。 |',
      '| 4 | Examples | 用 3 到 5 个 check-expect 展示函数应该如何工作。 |',
      '| 5 | Stub | 只写对函数名、参数数量和返回类型，用正确类型的 dummy result。 |',
      '| 6 | Template | 根据数据形状选择逻辑框架，不直接凭感觉写 body。 |',
      '| 7 | Function Body | 最后才写真正执行的函数逻辑。 |',
      '',
      '### Stub dummy result 对照',
      '| Output type | Stub result |',
      '| --- | --- |',
      '| Number / Integer / Natural | 0 |',
      '| String | "" |',
      '| Image | empty-image |',
      '',
      '### HTDD 基础类型表',
      '| Type of Data | dd-template-rules | Template body |',
      '| --- | --- | --- |',
      '| Number | atomic-non-distinct | (... c) |',
      '| String | atomic-non-distinct | (... c) |',
      '| Boolean | atomic-non-distinct | (... c) |',
      '| Image | atomic-non-distinct | (... c) |',
      '| Interval | atomic-non-distinct | (... c) |',
      '| "red" | atomic-distinct | (...) |',
      '| false | atomic-distinct | (...) |',
      '| empty | atomic-distinct | (...) |',
      '',
      '### One-of 条件判断表',
      '| Type of Data | dd-template-rules | Template | Cond question |',
      '| --- | --- | --- | --- |',
      '| Number | atomic-non-distinct | (... c) | (number? x) |',
      '| String | atomic-non-distinct | (... c) | (string? x) |',
      '| Boolean | atomic-non-distinct | (... c) | (boolean? x) |',
      '| Image | atomic-non-distinct | (... c) | (image? x) |',
      '| Interval | atomic-non-distinct | (... c) | (and (<= 1 x) (<= x 10)) |',
      '| "red" | atomic-distinct | (...) | (string=? x "red") |',
      '| false | atomic-distinct | (...) | (false? x) |',
      '| empty | atomic-distinct | (...) | (empty? x) |',
      '',
      '## Racket 代码参考',
      '```racket',
      '(@htdf circle-area)',
      '(@signature Number -> Number)',
      ';; calculate the area of a circle by given radius',
      '(check-expect (circle-area 0) 0)',
      '(check-within (circle-area 1) 3.14 0.01)',
      ';(define (circle-area r) 0) ;stub',
      '',
      '(@template-origin Number)',
      '(@template',
      ' (define (circle-area r)',
      '   (... r)))',
      '',
      '(define (circle-area r)',
      '  (* 3.14 (* r r)))',
      '',
      '(@htdf next-color)',
      '(@signature Natural -> Natural)',
      ';; produce the next color of a traffic light',
      '(check-expect (next-color 0) 2)',
      '(check-expect (next-color 1) 0)',
      '(check-expect (next-color 2) 1)',
      ';(define (next-color c) 0) ;stub',
      '',
      '(@template-origin Natural)',
      '(@template',
      ' (define (next-color c)',
      '   (... c)))',
      '',
      '(define (next-color c)',
      '  (if (= c 0)',
      '      2',
      '      (if (= c 1)',
      '          0',
      '          1)))',
      '',
      '(@htdd SeatNumber)',
      ';; SeatNumber is an Integer',
      ';; interp. seat number in a row, 1 and 32 are aisle seats',
      '(define START 1)',
      '(define MID 16)',
      '(define END 32)',
      '',
      '(@dd-template-rules atomic-non-distinct)',
      '(define (fn-for-seatnumber sn)',
      '  (... sn))',
      '',
      ';; LetterGrade is one of:',
      ';; - "A"',
      ';; - "B"',
      ';; - "C"',
      ';; interp. The letter grade in the course',
      ';; Examples are redundant for enumerations.',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    atomic-distinct',
      '                    atomic-distinct)',
      '',
      '(define (fn-for-letter-grade lg)',
      '  (cond [(string=? lg "A") (...)]',
      '        [(string=? lg "B") (...)]',
      '        [(string=? lg "C") (...)]))',
      '',
      '(@htdd CountDown)',
      ';; CountDown is one of:',
      ';; - false',
      ';; - Natural[1, 10]',
      ';; - "complete"',
      ';; interp.',
      ';;   false means countdown is not started',
      ';;   Natural[1, 10] means countdown is running',
      ';;   "complete" means countdown is completed',
      '(define CD1 false)',
      '(define CD2 1)',
      '(define CD3 10)',
      '(define CD4 "complete")',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    atomic-non-distinct',
      '                    atomic-distinct)',
      '',
      '(define (fn-for-count-down c)',
      '  (cond [(false? c) (...)]',
      '        [(and (number? c) (<= 1 c) (<= c 10)) (... c)]',
      '        [else (...)]))',
      '',
      '(@htdd Ball)',
      '(define-struct ball (x y))',
      ';; Ball is (make-ball Number Number)',
      ';; interp. a ball at position x, y',
      '(define BALL-1 (make-ball 6 10))',
      '',
      '(@dd-template-rules compound)',
      '(define (fn-for-ball b)',
      '  (... (ball-x b)',
      '       (ball-y b)))',
      '',
      '(@htdd Student)',
      '(define-struct student (id name major))',
      ';; Student is (make-student Number String String)',
      ";; interp. a student's information",
      ';;         id is the id of a student',
      ';;         name is the student name',
      ";;         major is the student's major",
      '(define SD1 (make-student 101 "Andy" "CS"))',
      '(define SD2 (make-student 301 "Oscar" "Math"))',
      '',
      '(@dd-template-rules compound)',
      '(define (fn-for-student s)',
      '  (... (student-id s)',
      '       (student-name s)',
      '       (student-major s)))',
      '```',
    ].join('\n'),
  },
  'nb-cpsc107-ref-self-ref-week4-20260519140849': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- Reference 指一个数据定义包含另一个已经定义好的数据定义，例如 Game 里面有 Ball。',
      '- Reference template 的核心动作：遇到自定义数据字段时，不直接拆字段内部，而是调用对应的 helper template。',
      '- Self-reference 指数据定义递归引用自己；ListOfX 的 rest 仍然是 ListOfX，是最典型的 self-ref。',
      '- Racket list 的基本构造和读取：empty、cons、list、quasiquote、first、second、third、fourth、rest。',
      '- 常见 list operations：length、member?、append、reverse、empty?。',
      '- ListOf primitive data 的模板：empty 分支是 atomic-distinct，cons 分支是 compound，rest 分支是 self-ref。',
      '- List of compound data 的模板：first 是 ref，调用 compound item 的 helper。',
      '- 在 List of compound 里，rest 是 self-ref，要递归调用当前 template。',
      '- 考试型递归数据定义包括 Waldo、Peat 这类 one-of itemization，需要同时识别 atomic-distinct、compound、self-ref。',
      '',
      '## 讲解重点',
      '- 用 Ball / Game 先讲 reference：Game 的 ball 字段已经是 Ball，所以 template 里写 fn-for-ball。',
      '- 用 cons 链讲 self-reference：empty 是 base case，(cons X ListOfX) 是 recursive case。',
      '- 讲 first / rest 时强调：first 拿当前元素，rest 拿剩余同类型 list，因此 rest 对应递归调用。',
      '- 讲 ListOfString 时让学生看到它和 ListOfInteger 只有元素类型变了，模板结构不变。',
      '- 讲 ListOfBook、ListOfDot 时强调同时出现 ref 和 self-ref：first 调 helper，rest 递归。',
      '- 做 Waldo / Peat 题时先逐行标 rule，再写 cond；每个分支必须有合适的 type predicate 或 distinct-value 判断。',
      '- 最后一类 atomic-distinct 分支通常可以用 else，但前面的 string 分支要先 guard，避免对非 string 调 string=?。',
      '',
      '## PDF 表格整理',
      '',
      '### Reference 与 Self-Reference',
      '| 概念 | 数据形状 | Template 动作 | PDF 例子 |',
      '| --- | --- | --- | --- |',
      '| Reference | 字段引用另一个已定义数据 | 调用对应 helper template | Game contains Ball |',
      '| Self-reference | 数据定义引用自己 | 对递归字段调用当前 template | rest of ListOfInteger |',
      '| Reference + self-reference | list 元素是 compound/custom data | first 调 helper，rest 递归 | ListOfDot |',
      '',
      '### List 操作记忆表',
      '| Operation | 用途 | PDF 例子含义 |',
      '| --- | --- | --- |',
      '| cons | 往 list 前面加一个元素 | (cons 1 (cons 2 empty)) |',
      '| list | 简便构造 list | (list 1 2 3) |',
      '| first / second / third / fourth | 读取指定位置元素 | (first L7) 产生 1 |',
      '| rest | 去掉第一个元素，得到剩余 list | (rest L7) 产生 (list 2 3 4 5 6 7) |',
      '| length | 计算 list 长度 | (length L7) 产生 7 |',
      '| member? | 判断元素是否在 list 中 | (member? 2 L7) 产生 true |',
      '| append | 合并两个 list | append 两个 list 得到更长 list |',
      '| reverse | 反转 list 顺序 | (reverse (list 1 2 3 4)) 产生 (list 4 3 2 1) |',
      '| empty? | 判断 list 是否为空 | (empty? empty) 产生 true |',
      '',
      '### Template rule 对照表',
      '| 数据定义形状 | dd-template-rules | Template 写法重点 |',
      '| --- | --- | --- |',
      '| compound only | compound | 用 selector 取每个字段 |',
      '| compound with custom field | compound + ref | 自定义字段调用 helper，如 fn-for-ball |',
      '| ListOf primitive | one-of + atomic-distinct + compound + self-ref | empty 分支结束；first 直接使用；rest 递归 |',
      '| List of compound | one-of + atomic-distinct + compound + ref + self-ref | first 调 helper；rest 递归 |',
      '| Recursive itemization | one-of + compound + self-ref + atomic-distinct | 先识别分支，再在递归字段调用当前 template |',
      '',
      '## Racket 代码参考',
      '```racket',
      ';; Reference: Game contains Ball.',
      '(@htdd Ball)',
      '(define-struct ball (x y))',
      ';; Ball is (make-ball Number Number)',
      ';; interp. a ball at position x, y',
      '(define BALL-1 (make-ball 6 10))',
      '',
      '(@dd-template-rules compound)',
      '(define (fn-for-ball b)',
      '  (... (ball-x b)',
      '       (ball-y b)))',
      '',
      '(@htdd Game)',
      '(define-struct game (ball score))',
      ';; Game is (make-game Ball Number)',
      ';; interp. current game state with the ball and score',
      '(define GAME-1 (make-game (make-ball 1 5) 2))',
      '',
      '(@dd-template-rules compound',
      '                    ref)',
      '(define (fn-for-game g)',
      '  (... (fn-for-ball (game-ball g))',
      '       (game-score g)))',
      '',
      ';; Self-reference: rest of ListOfInteger is another ListOfInteger.',
      '(@htdd ListOfInteger)',
      ';; ListOfInteger is one of:',
      ';; - empty',
      ';; - (cons Integer ListOfInteger)',
      ';; interp. a list of integers',
      '(define LOI0 empty)',
      '(define LOI1 (cons 212 (cons -98 (cons 3 empty))))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    self-ref)',
      '(define (fn-for-loi loi)',
      '  (cond [(empty? loi) (...)]',
      '        [else',
      '         (... (first loi)',
      '              (fn-for-loi (rest loi)))]))',
      '',
      '(@htdd ListOfString)',
      ';; ListOfString is one of:',
      ';; - empty',
      ';; - (cons String ListOfString)',
      ';; interp. a list of strings',
      '(define LOS-1 empty)',
      '(define LOS-2 (cons "a" empty))',
      '(define LOS-3 (cons "b" (cons "c" empty)))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    self-ref)',
      '(define (fn-for-los los)',
      '  (cond [(empty? los) (...)]',
      '        [else',
      '         (... (first los)',
      '              (fn-for-los (rest los)))]))',
      '',
      ';; List of compound data: first is a reference, rest is self-reference.',
      '(@htdd Book)',
      '(define-struct book (title auth year genre))',
      ';; Book is (make-book String String Natural String)',
      ';; interp. a book with title, author, year, and genre',
      '(define B1',
      '  (make-book "The Hate U Give"',
      '             "Angie Thomas"',
      '             2017',
      '             "Young Adult"))',
      '',
      '(@dd-template-rules compound)',
      '(define (fn-for-book b)',
      '  (... (book-title b)',
      '       (book-auth b)',
      '       (book-year b)',
      '       (book-genre b)))',
      '',
      '(@htdd ListOfBook)',
      ';; ListOfBook is one of:',
      ';; - empty',
      ';; - (cons Book ListOfBook)',
      ';; interp. a list of books',
      '(define LOB0 empty)',
      '(define LOB1 (cons B1 empty))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    ref',
      '                    self-ref)',
      '(define (fn-for-lob lob)',
      '  (cond [(empty? lob) (...)]',
      '        [else',
      '         (... (fn-for-book (first lob))',
      '              (fn-for-lob (rest lob)))]))',
      '',
      '(@htdd Dot)',
      '(define-struct dot (x y))',
      ';; Dot is (make-dot Integer Integer)',
      ';; interp. a dot on the screen, with x and y coordinates',
      '(define D1 (make-dot 10 30))',
      '',
      '(@dd-template-rules compound)',
      '(define (fn-for-dot d)',
      '  (... (dot-x d)',
      '       (dot-y d)))',
      '',
      '(@htdd ListOfDot)',
      ';; ListOfDot is one of:',
      ';; - empty',
      ';; - (cons Dot ListOfDot)',
      ';; interp. a list of dots',
      '(define LOD1 empty)',
      '(define LOD2 (cons (make-dot 10 20)',
      '                   (cons (make-dot 3 6) empty)))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    ref',
      '                    self-ref)',
      '(define (fn-for-lod lod)',
      '  (cond [(empty? lod) (...)]',
      '        [else',
      '         (... (fn-for-dot (first lod))',
      '              (fn-for-lod (rest lod)))]))',
      '```',
      '',
      '## 考试题型模板',
      '```racket',
      '(@htdd Waldo)',
      '(define-struct fie (a b))',
      '(define-struct foe (c d))',
      ';; Waldo is one of:',
      ';; - "fee"',
      ';; - "floo"',
      ';; - (make-fie Integer String)',
      ';; - (make-foe Number Waldo)',
      ';; - true',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    atomic-distinct',
      '                    compound',
      '                    compound',
      '                    self-ref',
      '                    atomic-distinct)',
      '(define (fn-for-waldo w)',
      '  (cond [(and (string? w) (string=? w "fee")) (...)]',
      '        [(string? w) (...)]',
      '        [(fie? w)',
      '         (... (fie-a w)',
      '              (fie-b w))]',
      '        [(foe? w)',
      '         (... (foe-c w)',
      '              (fn-for-waldo (foe-d w)))]',
      '        [else (...)]))',
      '',
      '(@htdd Peat)',
      '(define-struct crim (k d))',
      '(define-struct rudz (s b))',
      ';; Peat is one of:',
      ';; - (make-crim Integer Peat)',
      ';; - (make-rudz String Number)',
      ';; - false',
      ';; - "zap"',
      '',
      '(@dd-template-rules one-of',
      '                    compound',
      '                    self-ref',
      '                    compound',
      '                    atomic-distinct',
      '                    atomic-distinct)',
      '(define (fn-for-peat p)',
      '  (cond [(crim? p)',
      '         (... (crim-k p)',
      '              (fn-for-peat (crim-d p)))]',
      '        [(rudz? p)',
      '         (... (rudz-s p)',
      '              (rudz-b p))]',
      '        [(false? p) (...)]',
      '        [else (...)]))',
      '```',
    ].join('\n'),
  },
  'nb-cpsc107-recursion-bst-imagegen-20260522': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- Recursion 的核心是把当前问题拆成 base case 和 smaller problem；数学递归里要看 recurrence 需要几个 base cases。',
      '- List recursion 里 empty 是 base case，(rest loi) 是同类型的更小问题，template 来自 ListOfInteger 的 self-reference。',
      '- Helper function 来自 template：当一个数据定义引用另一个自定义数据时，外层函数只拆外层，内层交给对应 helper。',
      '- Package / Gift / Dimensions 例题展示 compound、one-of、reference 三种数据定义如何配合。',
      '- Tree 是无环的层级结构，包含 root、parent、sibling、children、ancestor、descendant、depth、height、subtree 等术语。',
      '- Binary tree 每个节点最多两个子树；BST 在 binary tree 基础上加入左小右大的 invariant。',
      '- BST lookup 根据 target 和当前 node key 的比较结果，只进入左子树或右子树，不需要遍历整棵树。',
      '',
      '## 讲解重点',
      '- 讲递归时先问停止条件是什么，再问每一步如何让问题变小。',
      '- 讲 list template 时强调 first 代表当前元素，rest 代表剩余同类型 list，所以 rest 对应 recursive call。',
      '- 讲 helper 时不要说成“为了省代码”，而要说成“模板要求”：Package contains Gift，所以 Package 函数调用 Gift helper。',
      '- 讲 package-required-dims 时把职责拆开：Package 层只取 contents；Gift 层根据 ball / block 决定尺寸。',
      '- 讲 tree 术语时要把 depth 和 height 区分开：depth 从 root 往下数，height 从当前 node 往最远 leaf 数。',
      '- 讲 BST 时先建立 invariant，再解释为什么 lookup-key 的每一步都能丢掉半边搜索空间。',
      '',
      '## PDF 表格整理',
      '',
      '### Recursion 与 List Template',
      '| 数据形状 | Base case | Recursive case | Template 动作 |',
      '| --- | --- | --- | --- |',
      '| Natural recursion | 0 或 1 等停止值 | n 的更小值 | 对更小的 Natural 调用当前函数 |',
      '| Fibonacci recursion | recurrence 要访问 n - 1 和 n - 2，所以需要两个 base cases | 两个 recursive calls | 每条递归分支都必须能停到 base case |',
      '| ListOfInteger | empty | (cons Integer ListOfInteger) | first 处理当前整数，rest 递归 |',
      '',
      '### Package / Gift 职责表',
      '| 数据定义 | 数据形状 | Template 重点 | 真实函数职责 |',
      '| --- | --- | --- | --- |',
      '| Gift | ball 或 block | cond 分 ball? / block? | ball 用 diameter，block 直接取三边 |',
      '| Package | to 和 contents | contents 是 Gift，所以调 helper | 取出 contents 交给 gift-required-dims |',
      '| Dimensions | w、l、h 三个字段 | selector 取三边 | 作为结果数据被 make-dims 产生 |',
      '',
      '### Tree 术语表',
      '| 术语 | 记忆点 |',
      '| --- | --- |',
      '| root | 树的起点，没有 parent |',
      '| parent / children | 直接上一级和直接下一级节点 |',
      '| sibling | 同一个 parent 的 children 互为 sibling |',
      '| ancestor / descendant | 从 root 到当前点路径上的上游节点；以及当前点往下的所有后代 |',
      '| depth | 从 root 到该 node 的边数，root depth 为 0 |',
      '| height | 从该 node 到最远 leaf 的边数 |',
      '| subtree | 以某个 node 为 root，包含它和所有 descendants 的树 |',
      '',
      '### BST Lookup 判断表',
      '| 当前情况 | 结果或下一步 | 原因 |',
      '| --- | --- | --- |',
      '| bst 是 false | false | 空树里找不到 target |',
      '| target = node key | true | 当前节点就是目标 |',
      '| target < node key | 搜 left subtree | BST invariant 保证右边都更大 |',
      '| target > node key | 搜 right subtree | BST invariant 保证左边都更小 |',
      '',
      '## Racket 代码参考',
      '```racket',
      '(@htdd ListOfInteger)',
      ';; ListOfInteger is one of:',
      ';; - empty',
      ';; - (cons Integer ListOfInteger)',
      ';; interp. a list of integers',
      '(define LOI0 empty)',
      '(define LOI1 (list 3 1 2 4 7))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    self-ref)',
      '(define (fn-for-loi loi)',
      '  (cond [(empty? loi) (...)]',
      '        [else',
      '         (... (first loi)',
      '              (fn-for-loi (rest loi)))]))',
      '',
      '(@htdf multiply-odds)',
      '(@signature ListOfInteger -> Integer)',
      ';; produce the product of all odd integers in loi',
      '(check-expect (multiply-odds empty) 1)',
      '(check-expect (multiply-odds (list 2 4 6)) 1)',
      '(check-expect (multiply-odds (list 3 1 2 4 7)) 21)',
      ';(define (multiply-odds loi) 1) ;stub',
      '',
      '(@template-origin ListOfInteger)',
      '(@template',
      ' (define (multiply-odds loi)',
      '   (cond [(empty? loi) (...)]',
      '         [else',
      '          (... (first loi)',
      '               (multiply-odds (rest loi)))])))',
      '',
      '(define (multiply-odds loi)',
      '  (cond [(empty? loi) 1]',
      '        [else',
      '         (if (odd? (first loi))',
      '             (* (first loi)',
      '                (multiply-odds (rest loi)))',
      '             (multiply-odds (rest loi)))]))',
      '',
      '(@htdd Gift)',
      '(define-struct ball (radius))',
      '(define-struct block (width length height))',
      ';; Gift is one of:',
      ';; - (make-ball Natural)',
      ';; - (make-block Natural Natural Natural)',
      ';; interp. a gift. A ball has a radius; a block has dimensions.',
      ';; CONSTRAINT: all measurements are greater than 0',
      '(define G-BALL (make-ball 2))',
      '(define G-BLOCK (make-block 3 4 5))',
      '',
      '(@dd-template-rules one-of',
      '                    compound',
      '                    compound)',
      '(define (fn-for-gift g)',
      '  (cond [(ball? g) (... (ball-radius g))]',
      '        [(block? g)',
      '         (... (block-width g)',
      '              (block-length g)',
      '              (block-height g))]))',
      '',
      '(@htdd Package)',
      '(define-struct package (to contents))',
      ';; Package is (make-package String Gift)',
      ';; interp. a package recipient and the gift inside',
      '(define P-BALL (make-package "Gregor" G-BALL))',
      '(define P-BLOCK (make-package "Emily" G-BLOCK))',
      '',
      '(@dd-template-rules compound',
      '                    ref)',
      '(define (fn-for-package p)',
      '  (... (package-to p)',
      '       (fn-for-gift (package-contents p))))',
      '',
      '(@htdd Dimensions)',
      '(define-struct dims (w l h))',
      ';; Dimensions is (make-dims Number Number Number)',
      ';; interp. width, length, and height of a box in centimeters',
      '',
      '(@htdf package-required-dims gift-required-dims)',
      '(@signature Package -> Dimensions)',
      '(@signature Gift -> Dimensions)',
      ';; produce required internal package dimensions for p',
      ';; produce required internal package dimensions for g',
      '(check-expect (package-required-dims P-BALL) (make-dims 4 4 4))',
      '(check-expect (package-required-dims P-BLOCK) (make-dims 3 4 5))',
      ';(define (package-required-dims p) (make-dims 1 1 1)) ;stub',
      ';(define (gift-required-dims g) (make-dims 1 1 1)) ;stub',
      '',
      '(@template-origin Package)',
      '(@template',
      ' (define (package-required-dims p)',
      '   (... (package-to p)',
      '        (gift-required-dims (package-contents p)))))',
      '',
      '(define (package-required-dims p)',
      '  (gift-required-dims (package-contents p)))',
      '',
      '(@template-origin Gift)',
      '(@template',
      ' (define (gift-required-dims g)',
      '   (cond [(ball? g) (... (ball-radius g))]',
      '         [(block? g)',
      '          (... (block-width g)',
      '               (block-length g)',
      '               (block-height g))])))',
      '',
      '(define (gift-required-dims g)',
      '  (cond [(ball? g)',
      '         (make-dims (* 2 (ball-radius g))',
      '                    (* 2 (ball-radius g))',
      '                    (* 2 (ball-radius g)))]',
      '        [(block? g)',
      '         (make-dims (block-width g)',
      '                    (block-length g)',
      '                    (block-height g))]))',
      '```',
      '',
      '## BST 代码参考',
      '```racket',
      '(@htdd BST)',
      '(define-struct node (key left right))',
      ';; BST is one of:',
      ';; - false',
      ';; - (make-node Integer BST BST)',
      ';; interp. false means empty tree; node stores a key and subtrees',
      ';; INVARIANT: all keys in left are less than key,',
      ';;            all keys in right are greater than key,',
      ';;            and no key appears twice',
      '(define BST0 false)',
      '(define BST1 (make-node 1 false false))',
      '(define BST4 (make-node 4 false (make-node 7 false false)))',
      '(define BST3 (make-node 3 BST1 BST4))',
      '(define BST42',
      '  (make-node 42',
      '             (make-node 27 (make-node 14 false false) false)',
      '             (make-node 50 false false)))',
      '(define BST10 (make-node 10 BST3 BST42))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    self-ref',
      '                    self-ref)',
      '(define (fn-for-bst bst)',
      '  (cond [(false? bst) (...)]',
      '        [else',
      '         (... (node-key bst)',
      '              (fn-for-bst (node-left bst))',
      '              (fn-for-bst (node-right bst)))]))',
      '',
      '(@htdf lookup-key)',
      '(@signature Integer BST -> Boolean)',
      ';; produce true if bst contains target key',
      '(check-expect (lookup-key 10 BST0) false)',
      '(check-expect (lookup-key 1 BST10) true)',
      '(check-expect (lookup-key 50 BST10) true)',
      '(check-expect (lookup-key 99 BST10) false)',
      ';(define (lookup-key target bst) false) ;stub',
      '',
      '(@template-origin BST)',
      '(@template',
      ' (define (lookup-key target bst)',
      '   (cond [(false? bst) (...)]',
      '         [else',
      '          (... target',
      '               (node-key bst)',
      '               (lookup-key target (node-left bst))',
      '               (lookup-key target (node-right bst)))])))',
      '',
      '(define (lookup-key target bst)',
      '  (cond [(false? bst) false]',
      '        [(= target (node-key bst)) true]',
      '        [(< target (node-key bst))',
      '         (lookup-key target (node-left bst))]',
      '        [else',
      '         (lookup-key target (node-right bst))]))',
      '```',
    ].join('\n'),
  },
  'nb-cpsc107-trees-mutual-recursion-imagegen-20260522': {
    title: '涉及知识点与讲解重点',
    text: [
      '## 涉及知识点',
      '- Reference classification 包括 R、SR、MR：R 是普通引用，SR 是自引用，MR 是多个数据定义形成引用环。',
      '- Function recursion classification 包括 NH、NR、NMR：NH 是 helper call，NR 是函数直接调用自己，NMR 是多个函数互相调用形成环。',
      '- 判断 MR / NMR 时要把数据定义或函数调用画成图，看是否存在从一个点走出去又回到同一个点的 cycle。',
      '- Arbitrary-branch tree 可以用 Node 和 ListOfNode 两个互相引用的数据定义表示。',
      '- Node 函数负责当前 node 的 value 和 children；ListOfNode 函数负责 empty / first / rest。',
      '- Mutually recursive functions 必须成对设计：一个函数处理 Node，一个函数处理 ListOfNode。',
      '- sum--node / sum--lon 展示树上所有 value 求和；greater-than--node / greater-than--lon 展示树上筛选并 append 结果。',
      '- Course / ListOfCourse 是正式命名模式：course-dependents 是 ListOfCourse，所以 all-course-numbers 也要拆成两个函数。',
      '',
      '## 讲解重点',
      '- 先判断最容易的 self-reference：ListOfX 的 rest 指回 ListOfX，通常是 SR。',
      '- 再找环：如果 A 包含 B，B 又经由某条路径包含 A，这些箭头属于 mutual reference。',
      '- 区分 data graph 和 function call graph：数据里的 MR 通常会导出函数里的 NMR，但标注时要看题目问的是哪一种。',
      '- 讲 tree traversal 时用固定口令：node 处理当前值，lon 处理一串孩子。',
      '- 讲 sum 时强调 empty 的 identity 是 0；讲 greater-than 时强调 empty 的 identity 是 empty，兄弟子树结果用 append 合并。',
      '- 讲 Course 例题时把 current course number 用 cons 放前面，把 dependents 的结果交给 ListOfCourse helper。',
      '',
      '## PDF 表格整理',
      '',
      '### Reference / Recursion 标签表',
      '| 标签 | 全称 | 判断方式 | PDF 例子 |',
      '| --- | --- | --- | --- |',
      '| R | reference | 只引用另一个数据定义，没有形成环 | Employee 到 ListOfGrant；Baz 到 Zorker |',
      '| SR | self-reference | 数据定义直接或通过 rest 指回自己 | ListOfEmployee 的 rest；ListOfFoo 的 rest |',
      '| MR | mutual-reference | 两个或多个数据定义形成环 | Employee 和 ListOfEmployee；Foo、Baz、ListOfFoo |',
      '| NH | natural helper | 函数调用另一个 helper，没有递归环 | fn-for-baz 调 fn-for-zorker |',
      '| NR | natural recursion | 函数直接调用自己 | fn-for-lof 调 fn-for-lof |',
      '| NMR | natural mutual recursion | 多个函数互相调用形成环 | fn-for-foo、fn-for-baz、fn-for-lof 形成 cycle |',
      '',
      '### PDF 例题答案整理',
      '| 题目 | 最容易先判 | Mutual-reference 环 | 普通 reference |',
      '| --- | --- | --- | --- |',
      '| Employee / Grant | D、F 是 SR | A、C 是 MR，因为 Employee 和 ListOfEmployee 互相包含 | B、E 是 R |',
      '| Foo / Baz / Zorker / ListOfFoo | E 是 SR | A、C、D 是 MR，因为 Foo、Baz、ListOfFoo 形成环 | B 是 R |',
      '',
      '### Tree 函数职责表',
      '| 函数层级 | 输入类型 | 负责什么 | 常见组合方式 |',
      '| --- | --- | --- | --- |',
      '| node function | Node | 当前 value，加上 children 的结果 | 使用 node selector，然后调用 lon helper |',
      '| lon function | ListOfNode | empty / first / rest | empty 给 identity；first 调 node helper；rest 递归 |',
      '| sum traversal | Number result | 把所有值加起来 | empty -> 0，组合用 + |',
      '| filter traversal | List result | 收集满足条件的 value | empty -> empty，兄弟结果用 append |',
      '',
      '## Racket 代码参考',
      '```racket',
      '(@htdd Node ListOfNode)',
      '(define-struct node (val children))',
      ';; Node is (make-node Number ListOfNode)',
      ';; interp. a tree node with a value and a list of children',
      ';; ListOfNode is one of:',
      ';; - empty',
      ';; - (cons Node ListOfNode)',
      ';; interp. a list of tree nodes',
      '(define N2 (make-node 2 empty))',
      '(define N3 (make-node 3 empty))',
      '(define N5 (make-node 5 empty))',
      '(define N7 (make-node 7 empty))',
      '(define T1 (make-node 1 (list N2 N7)))',
      '(define T2 (make-node 4 (list T1 N3 N5)))',
      '',
      '(@dd-template-rules compound',
      '                    ref)',
      '(define (fn-for-node n)',
      '  (... (node-val n)',
      '       (fn-for-lon (node-children n))))',
      '',
      '(@dd-template-rules one-of',
      '                    atomic-distinct',
      '                    compound',
      '                    ref',
      '                    self-ref)',
      '(define (fn-for-lon lon)',
      '  (cond [(empty? lon) (...)]',
      '        [else',
      '         (... (fn-for-node (first lon))',
      '              (fn-for-lon (rest lon)))]))',
      '',
      '(@htdf sum--node sum--lon)',
      '(@signature Node -> Number)',
      '(@signature ListOfNode -> Number)',
      ';; produce sum of all node values in n',
      ';; produce sum of all node values in lon',
      '(check-expect (sum--lon empty) 0)',
      '(check-expect (sum--node N2) 2)',
      '(check-expect (sum--node T2) 22)',
      ';(define (sum--node n) 0) ;stub',
      ';(define (sum--lon lon) 0) ;stub',
      '',
      '(@template-origin Node)',
      '(@template',
      ' (define (sum--node n)',
      '   (... (node-val n)',
      '        (sum--lon (node-children n)))))',
      '',
      '(define (sum--node n)',
      '  (+ (node-val n)',
      '     (sum--lon (node-children n))))',
      '',
      '(@template-origin ListOfNode)',
      '(@template',
      ' (define (sum--lon lon)',
      '   (cond [(empty? lon) (...)]',
      '         [else',
      '          (... (sum--node (first lon))',
      '               (sum--lon (rest lon)))])))',
      '',
      '(define (sum--lon lon)',
      '  (cond [(empty? lon) 0]',
      '        [else',
      '         (+ (sum--node (first lon))',
      '            (sum--lon (rest lon)))]))',
      '',
      '(@htdd ListOfNumber)',
      ';; ListOfNumber is one of:',
      ';; - empty',
      ';; - (cons Number ListOfNumber)',
      ';; interp. a list of numbers',
      '',
      '(@htdf greater-than--node greater-than--lon)',
      '(@signature Node Number -> ListOfNumber)',
      '(@signature ListOfNode Number -> ListOfNumber)',
      ';; produce values in n that are greater than threshold',
      ';; produce values in lon that are greater than threshold',
      '(check-expect (greater-than--lon empty 3) empty)',
      '(check-expect (greater-than--node N2 3) empty)',
      '(check-expect (greater-than--node T2 3) (list 4 7 5))',
      ';(define (greater-than--node n threshold) empty) ;stub',
      ';(define (greater-than--lon lon threshold) empty) ;stub',
      '',
      '(@template-origin Node)',
      '(define (greater-than--node n threshold)',
      '  (if (> (node-val n) threshold)',
      '      (cons (node-val n)',
      '            (greater-than--lon (node-children n) threshold))',
      '      (greater-than--lon (node-children n) threshold)))',
      '',
      '(@template-origin ListOfNode)',
      '(define (greater-than--lon lon threshold)',
      '  (cond [(empty? lon) empty]',
      '        [else',
      '         (append (greater-than--node (first lon) threshold)',
      '                 (greater-than--lon (rest lon) threshold))]))',
      '```',
      '',
      '## Course / ListOfCourse 代码参考',
      '```racket',
      '(@htdd Course ListOfCourse)',
      '(define-struct course (number credits dependents))',
      ';; Course is (make-course Natural Natural ListOfCourse)',
      ';; interp. a course number, credits, and dependent courses',
      ';; ListOfCourse is one of:',
      ';; - empty',
      ';; - (cons Course ListOfCourse)',
      ';; interp. a list of courses',
      '(define C313 (make-course 313 3 empty))',
      '(define C317 (make-course 317 3 empty))',
      '(define LOC313-317 (list C313 C317))',
      '(define C213 (make-course 213 4 LOC313-317))',
      '',
      '(@htdd ListOfNatural)',
      ';; ListOfNatural is one of:',
      ';; - empty',
      ';; - (cons Natural ListOfNatural)',
      ';; interp. a list of natural numbers',
      '',
      '(@htdf all-course-numbers--course all-course-numbers--loc)',
      '(@signature Course -> ListOfNatural)',
      '(@signature ListOfCourse -> ListOfNatural)',
      ';; produce all course numbers in c and its dependents',
      ';; produce all course numbers in loc and their dependents',
      '(check-expect (all-course-numbers--loc empty) empty)',
      '(check-expect (all-course-numbers--course C313) (list 313))',
      '(check-expect (all-course-numbers--course C213) (list 213 313 317))',
      ';(define (all-course-numbers--course c) empty) ;stub',
      ';(define (all-course-numbers--loc loc) empty) ;stub',
      '',
      '(@template-origin Course)',
      '(define (all-course-numbers--course c)',
      '  (cons (course-number c)',
      '        (all-course-numbers--loc (course-dependents c))))',
      '',
      '(@template-origin ListOfCourse)',
      '(define (all-course-numbers--loc loc)',
      '  (cond [(empty? loc) empty]',
      '        [else',
      '         (append (all-course-numbers--course (first loc))',
      '                 (all-course-numbers--loc (rest loc)))]))',
      '```',
    ].join('\n'),
  },
};

const mat102InductionPublicMemory: DefaultPublicMemoryDefinition = {
  title: 'MAT102 归纳法、强归纳与结构归纳',
  text: [
    '## 核心知识',
    '- 数学归纳法用 base case 和 induction step 证明 P(n) 对所有正整数成立。',
    '- 普通归纳的递推形式是：先证明 P(1)，再证明 P(k) 推出 P(k+1)。',
    '- 强归纳允许在证明 P(k+1) 时使用 P(1), P(2), ..., P(k)，适合新项依赖多个旧项的题。',
    '- 递归定义由 basis elements 和 constructors 组成；结构归纳按对象的生成规则证明性质。',
    '- Well-Ordering Principle 和 Induction 在课程中互相支撑，都是处理无限离散对象的基本工具。',
    '',
    '## 证明动作',
    '- 普通归纳证明要先明确定义 P(n) 和起始范围，再检查 base case。',
    '- Induction step 中先假设 P(k)，再把 P(k+1) 的目标式改写到能调用 P(k) 的形状。',
    '- 整除归纳题要把 divisibility 写成整数倍，再在 k+1 层整理出同一个整数倍结构。',
    '- 求和归纳题把前 k+1 项拆成“前 k 项旧和 + 新增最后一项”，再代入 induction hypothesis。',
    '- 强归纳题要写清楚假设范围，例如所有从起点到 n 的旧情形都可用。',
    '- 结构归纳题先证明每个 basis，再逐一证明每个 constructor 会保持目标性质。',
    '',
    '## 易错点',
    '- 检查很多具体 n 不是归纳证明；必须说明链条如何从起点推进到全体。',
    '- Base case 数量由递推依赖决定；若新项依赖前两项，通常需要两个 base cases。',
    '- Induction hypothesis 只能用于已经声明的旧命题，不能直接使用 P(k+1)。',
    '- 构造型归纳中要把大对象切回同类型的小对象，例如 L-tiling 棋盘要分成四个小棋盘。',
    '- 结构归纳不能只验 basis；每一种 constructor 都必须检查。',
  ].join('\n'),
};

const mat102PublicMemories: Record<string, DefaultPublicMemoryDefinition> = {
  'mat102-sets-propositions-proof-v2': {
    title: 'MAT102 集合与命题证明入口',
    text: [
      '## 核心知识',
      '- 集合是 unordered、well-defined、distinct objects 的收集；membership 用 in / not in 判断。',
      '- Set-builder notation 用性质描述集合，核心是把“x satisfies property P”翻译成可检查条件。',
      '- Union、intersection、difference、complement 和 Cartesian product 都以元素属于关系定义。',
      '- Complement 必须相对于 universe of discourse U；Cartesian product 的元素是 ordered pairs。',
      '- Subset 定义为 every element of S is also an element of T；set equality 等价于双向 subset。',
      '- Proposition 有确定真值；predicate 含变量，只有给变量取值后才变成 proposition。',
      '- AND、OR、NOT 的真值表用于判断 compound propositions，并证明 logical equivalence。',
      '',
      '## 证明动作',
      '- 证明 S subset T：任取 x in S，展开 S 的定义，最后推出 x in T。',
      '- 证明两个集合相等：分别证明 A subset B 和 B subset A。',
      '- 证明集合运算恒等式：先把 x in union/intersection/difference/complement 翻成 or/and/not，再做逻辑变形。',
      '- 处理 set-builder 例题：先明确 universe 和变量范围，再把存在的参数或性质写出来。',
      '- 证明逻辑等价：列出所有 P,Q 的真值组合，逐列计算两边，并比较结果列。',
      '',
      '## 易错点',
      '- 只看图像或直觉不能替代元素证明；subset 证明必须从任意元素开始。',
      '- 集合不看顺序，也不重复计算同一个元素。',
      '- 没有指定 U 时，complement 的含义不完整。',
      '- A x B 通常不同于 B x A，因为 ordered pair 的顺序也是数据。',
      '- 谓词还含自由变量时，不能直接说 true 或 false。',
      '- 数学里的 OR 是 inclusive OR：至少一个为真即可，两个都真也为真。',
    ].join('\n'),
  },
  'mat102-logic-quantifiers-proof-v2': {
    title: 'MAT102 量词、蕴含与否定',
    text: [
      '## 核心知识',
      '- Quantifiers 把 predicates 变成 propositions；forall 要覆盖全部对象，exists 只需要一个 witness。',
      '- 多重量词的顺序会改变含义，尤其是 forall x exists y 与 exists y forall x 的依赖关系不同。',
      '- 否定量词时，forall 变 exists，exists 变 forall，同时谓词取否定。',
      '- Implication P => Q 只有在 P true 且 Q false 时为 false。',
      '- Converse 是 Q => P；contrapositive 是 not Q => not P；原命题与逆否命题 logically equivalent。',
      '- Negation of implication 是 P and not Q，这也是寻找反例的精确形式。',
      '- If and only if 表示两个方向都成立：P => Q 和 Q => P。',
      '',
      '## 证明动作',
      '- 证明 forall：任取一个 arbitrary element，再证明它满足目标性质。',
      '- 证明 exists：构造一个具体 witness，并检查它满足谓词。',
      '- 反驳 forall：给出一个满足否定谓词的 counterexample。',
      '- 证明 P => Q：假设 P 成立，目标是推出 Q。',
      '- 用 contrapositive 证明：把 P => Q 改成 not Q => not P，常用于 parity 这类题。',
      '- 证明 iff：拆成两个 implication，两个方向分别写。',
      '',
      '## 易错点',
      '- 不同类量词通常不能交换；变量后出现的选择可能依赖前面的变量。',
      '- Counterexample 不是随便举例，而是必须让原命题失败、让否定命题成立。',
      '- Converse 不等价于原命题，不能把 Q => P 当成 P => Q 使用。',
      '- 否定 if-then 时不是把两边都否定，而是写成 P and not Q。',
      '- 日常语言里的 if、or、only if 不一定等同于数学逻辑，要回到真值定义。',
    ].join('\n'),
  },
  'mat102-relations-equivalence-orders-proof-v2': {
    title: 'MAT102 反证、关系与序结构',
    text: [
      '## 核心知识',
      '- Proof by contradiction 用“假设目标为假”推出矛盾，课程例子包括 pi 的十进制数字、sqrt(2) irrational、没有最小正实数。',
      '- Binary relation R between A and B 是 A x B 的一个 subset；aRb 意思是 (a,b) 被选入关系。',
      '- 关系性质包括 left-total、functional、reflexive、irreflexive、symmetric、anti-symmetric、transitive、total。',
      '- Equivalence relation 同时满足 reflexive、symmetric、transitive，并产生 equivalence classes。',
      '- 等价关系把集合 partition 成互不相交的 equivalence classes。',
      '- Weak order / poset 关注 reflexive、anti-symmetric、transitive；total order 要求任意两个元素可比较。',
      '- Maximal/minimal、maximum/minimum、upper/lower bound、supremum/infimum 是不同层级的序概念。',
      '',
      '## 证明动作',
      '- 反证法先写“for the sake of contradiction”，再明确反设包含哪些条件。',
      '- 验证关系性质前先把定义中的量词写出：任取哪些元素、假设哪些关系、要推出什么。',
      '- 证明 equivalence relation：分别验证 reflexive、symmetric、transitive。',
      '- 证明 equivalence class 结论：先证明覆盖，再证明相关元素给出同一类，最后证明不同类不相交。',
      '- 证明 poset：分别检查 reflexive、anti-symmetric、transitive，并用 counterexample 说明不是 total。',
      '- 找 maximal element 时要证明不存在更大的可比较元素；找 maximum 时要证明所有元素都小于等于它。',
      '',
      '## 易错点',
      '- 反证法的反设必须是否定整个目标，不是随便假设一个相反直觉。',
      '- Symmetric 和 anti-symmetric 不是互为否定。',
      '- Equivalence class 的代表元只是命名，同一个类可以有很多代表元。',
      '- Maximal 不等于 maximum；在 partial order 中可能有多个 maximal elements，也可能没有 maximum。',
      '- Upper bound 可以不在子集 S 里；supremum 是所有 upper bounds 里的 least one。',
    ].join('\n'),
  },
  'mat102-functions-i-proof-v2': {
    title: 'MAT102 函数、像集与单双射',
    text: [
      '## 核心知识',
      '- Function 是 left-total 且 functional 的 binary relation；每个 domain 元素有且只有一个 output。',
      '- f: A -> B 同时给出 domain、codomain 和 mapping rule；函数相等要求这些数据一致，并且每个输入输出一致。',
      '- Image f(U) 是 U 中元素经 f 送出的所有输出；preimage f^{-1}(V) 是输出落在 V 中的所有输入。',
      '- Preimage notation 不要求函数真的有 inverse function。',
      '- Injective 表示 f(s1)=f(s2) only if s1=s2；codomain 每个元素最多被打中一次。',
      '- Surjective 表示每个 codomain 元素至少被某个 domain 元素打中。',
      '- Bijective 表示 injective and surjective；每个目标元素恰好有一个 preimage。',
      '',
      '## 证明动作',
      '- 证明函数定义：检查 left-total 和 functional。',
      '- 证明 image 等式：通常用 double subset inclusion，先证明 y 在候选集合中能找到 x，再证明每个 f(x) 落回候选集合。',
      '- 求 preimage：把 f(x) in V 展开成关于输入 x 的条件。',
      '- 证明 injective：从 f(x)=f(y) 出发，推出 x=y。',
      '- 反驳 injective：找两个不同输入给出同一输出。',
      '- 证明 surjective：任取目标 t in codomain，构造输入 s 使 f(s)=t。',
      '- 反驳 surjective：找一个 codomain 元素无法被任何输入打中。',
      '- 证明 composite 保持 injective/surjective：按定义逐层使用两个函数的性质。',
      '',
      '## 易错点',
      '- 只写公式不够；domain 和 codomain 改变时，函数可能变成不同函数。',
      '- Preimage f^{-1}(V) 是集合操作，不等于 inverse function 存在。',
      '- Injective 和 surjective 的量词方向不同，证明开头也不同。',
      '- 判断 surjective 必须看 codomain，不是只看实际出现的输出集合。',
      '- Composition 的顺序是先 g 后 f，写 f circ g 时不要把 domain/codomain 接错。',
    ].join('\n'),
  },
  'mat102-functions-ii-cardinality-proof-v2': {
    title: 'MAT102 逆函数、基数与可数性',
    text: [
      '## 核心知识',
      '- Inverse function g of f: S -> T 要满足 g circ f = id_S 和 f circ g = id_T。',
      '- Function invertible 当且仅当 bijective；双射能为每个目标选出唯一 preimage。',
      '- Cardinality comparison |S| <= |T| 定义为存在 injection S -> T。',
      '- 对有限集合，|S| <= |T| 等价于元素个数 n <= m。',
      '- 如果 S -> T 有 surjection 且集合非空，也能推出 |T| <= |S|。',
      '- Infinite sets 可以和 proper subset 一样大，例如 N 与偶自然数。',
      '- Cantor-Schroder-Bernstein：若两边互相 injection，则 cardinalities equal。',
      '- Countable 表示能注入 N 或能列成 sequence；Z、Q、countable union of countable sets 都可数。',
      '- Real numbers uncountable；Cantor diagonal argument 证明 [0,1] 不可数。',
      '- Cantor theorem：|S| < |P(S)|，幂集总比原集合大。',
      '',
      '## 证明动作',
      '- 证明 inverse：检查两个 composition 是否都是 identity。',
      '- 证明 invertible implies bijective：分别证明 surjective 和 injective。',
      '- 证明 bijective implies invertible：用 surjective 给存在性，用 injective 给唯一性来定义 inverse。',
      '- 比较 cardinality：构造 injection、surjection、bijection，或用互相嵌入。',
      '- 证明 countable：给出明确编码或列表，例如把 Z 编进 N，把 Q 写成最简分数对。',
      '- 证明 uncountable：反设可列，构造 diagonal object 不在列表中。',
      '- 证明 Cantor theorem：先用 x -> {x} 给 injection，再用 diagonal set 证明没有 surjection S -> P(S)。',
      '',
      '## 易错点',
      '- Infinite subset 不一定更小；proper subset 也可能和原集合等势。',
      '- 可逆不是只“看起来能倒回去”，必须验证两个方向的 identity。',
      '- 构造 cardinality injection 时要避免不同输入撞到同一输出。',
      '- 对角线证明的关键是构造一个和列表中第 n 项在第 n 位不同的对象。',
      '- Dense 不等于 uncountable；Q 在 R 中 dense 但仍然 countable。',
    ].join('\n'),
  },
  'mat102-number-theory-i-euclidean-proof-v2': {
    title: 'MAT102 整除、gcd 与欧几里得算法',
    text: [
      '## 核心知识',
      '- Divisibility b | a 表示存在 integer k 使 a = bk，且 b non-zero。',
      '- 整除的基本性质包括 transitivity、linear combination、互相整除推出相差符号、非零整除带来绝对值大小约束。',
      '- Division Algorithm：对 a,b in Z 且 b>0，存在唯一 q,r 使 a=qb+r 且 0<=r<b。',
      '- gcd(a,b) 是同时整除 a,b 的最大正整数；coprime 表示 gcd(a,b)=1。',
      '- 若 a=bq+r，则 gcd(a,b)=gcd(b,r)，这是 Euclidean Algorithm 的核心。',
      '- Euclidean Algorithm 通过严格递减余数列有限终止，最后非零余数是 gcd。',
      '- Bezout identity：存在 m,n in Z 使 am+bn=gcd(a,b)。',
      '- gcd 也可由“公因数且可写成 a,b 的整数线性组合”刻画。',
      '',
      '## 证明动作',
      '- 证明整除命题：把 b | a 改写成 a=bk，并明确 k 是整数。',
      '- 用 Division Algorithm 分类：按余数 0,1,...,b-1 分情况证明。',
      '- 证明 gcd(a,b)=gcd(b,r)：证明两组 common divisors 完全相同。',
      '- 执行 Euclidean Algorithm：连续写 a=bq+r，再把 (a,b) 换成 (b,r)。',
      '- 求 Bezout coefficients：从最后的非零余数开始，沿欧几里得步骤反向回代。',
      '- 比较两个 gcd：证明两组公共因子相同，或证明其中一个是另一个的 divisor。',
      '',
      '## 易错点',
      '- b | a 的方向不要反；它表示 a 是 b 的倍数。',
      '- Division Algorithm 的余数必须满足 0<=r<b，唯一性依赖这个范围。',
      '- gcd 是 positive integer，除了约定 gcd(0,0)=0。',
      '- Euclidean Algorithm 中每一步 gcd 不变，不只是计算技巧。',
      '- Bezout coefficients 不唯一；找到一组整数系数即可。',
    ].join('\n'),
  },
  'mat102-number-theory-ii-primes-proof-v2': {
    title: 'MAT102 丢番图方程、素数与唯一分解',
    text: [
      '## 核心知识',
      '- 若 a | bc 且 gcd(a,b)=1，则 a | c；这是从 Bezout identity 到素数性质的关键引理。',
      '- Linear Diophantine Equation 形如 ax+by=c，课程关注 integer solutions。',
      '- ax+by=c 有整数解当且仅当 gcd(a,b) | c。',
      '- 一旦有一组解 (x0,y0)，所有解为 x=x0+n b/d，y=y0-n a/d，其中 d=gcd(a,b)。',
      '- Prime number 是大于 1 且不能写成两个更小自然数乘积的正整数。',
      '- p prime 当且仅当 p | ab 推出 p | a 或 p | b。',
      '- Fundamental Theorem of Arithmetic：每个大于 1 的正整数可唯一分解为素数乘积。',
      '- Euclid proof 说明 prime numbers infinitely many。',
      '',
      '## 证明动作',
      '- 解 LDE：先算 d=gcd(a,b)，检查 d 是否整除 c；若整除，用欧几里得回代找一组解。',
      '- 求通解：把任意解与特解相减，化成 a(x-x0)+b(y-y0)=0，再用 a/d 与 b/d 互素。',
      '- 求非负解：把通解代入不等式，筛选 integer parameter n。',
      '- 证明素数整除乘积性质：若 p 不整除 a，则 gcd(p,a)=1，再用互素引理推出 p | b。',
      '- 证明唯一分解存在性：用 well-ordering 取最小反例，再拆成更小因子。',
      '- 证明唯一性：用 prime divides product 性质逐个匹配两边素因子。',
      '- 证明素数无穷多：反设有限，构造 p1p2...pn + 1。',
      '',
      '## 易错点',
      '- LDE 有 rational solutions 不代表有 integer solutions；必须看 gcd(a,b) 是否整除 c。',
      '- 通解中的步长是 b/d 和 a/d，不是 b 和 a。',
      '- Prime 的乘积整除性质只对 prime 保证；composite number 可以失败。',
      '- 唯一分解的唯一性是“素因子和指数”唯一，不是写法顺序唯一。',
      '- 反证素数有限时，新数 p1...pn+1 不是简单说“它一定是素数”，而是它不能被列表中的素数整除。',
    ].join('\n'),
  },
  'mat102-number-theory-iii-modular-proof-v2': {
    title: 'MAT102 同余、模运算与费马小定理',
    text: [
      '## 核心知识',
      '- a congruent b mod n 定义为 n | (b-a)，同余本质上是整除语言。',
      '- Congruence mod n 是 equivalence relation，满足 reflexive、symmetric、transitive。',
      '- 若 a congruent r 且 b congruent s mod n，则 a+b congruent r+s，ab congruent rs。',
      '- 同余类把整数按余数分组；Z_n 中的加法和乘法通过代表元计算再取同余类。',
      '- Cancellation law 需要 gcd(p,x)=1；若 mx congruent nx mod p，可推出 m congruent n mod p。',
      '- Fermat Little Theorem：p prime 且 p 不整除 a 时，a^(p-1) congruent 1 mod p。',
      '- 推论：任意整数 a 和素数 p，都有 a^p congruent a mod p。',
      '- 若 p prime，则 Z_p 中每个 non-zero element 都有 multiplicative inverse。',
      '',
      '## 证明动作',
      '- 证明同余命题：先把 a congruent b mod n 改写成 n | (b-a)。',
      '- 验证同余是等价关系：分别用 0、差的相反数、差的相加证明三条性质。',
      '- 证明加法/乘法兼容：把两个同余写成 r-a=nk、s-b=n ell，再组合。',
      '- 做幂的末位或余数题：先在目标 modulus 下找周期，再化简指数。',
      '- 使用 cancellation：必须先确认被消掉的因子和 modulus coprime。',
      '- 证明 Fermat：把非零同余类乘以 a 后得到同一组类的重排，再比较整体乘积并消去。',
      '- 求 Z_p 中逆元：可用 Fermat 的 a^(p-2)，也可用 Bezout / Euclidean Algorithm 解 ax congruent 1。',
      '',
      '## 易错点',
      '- a congruent b mod n 不表示 a 和 b 大小接近，只表示差是 n 的倍数。',
      '- 不能在模运算中随意消因子；消去需要 coprime 条件。',
      '- Z_n 中非零元素不一定都有逆元；素数模 Z_p 才保证每个非零类可逆。',
      '- 选择代表元计算后，要回到同余类或指定余数范围。',
      '- Fermat Little Theorem 的 a^(p-1) 版本需要 p 不整除 a。',
    ].join('\n'),
  },
  'nb-mat102-zh-induction-i-20260519': mat102InductionPublicMemory,
  'nb-mat102-zh-induction-i-skill-v2-20260601': mat102InductionPublicMemory,
};

function isMat136Course(course: DefaultCoursePublicMemoryInput): boolean {
  const courseCode = course.courseCode?.trim().toUpperCase();
  if (courseCode === 'MAT136' || courseCode === 'MAT 136') return true;
  const haystack = [course.name, course.courseCode, ...(course.tags || [])]
    .filter((value): value is string => typeof value === 'string')
    .join(' ')
    .toUpperCase();
  return /\bMAT\s*136\b/.test(haystack);
}

export function getDefaultNotebookPublicMemories(stageId: string): DefaultPublicMemoryItem[] {
  const definition =
    mat136PublicMemories[stageId] ??
    cpsc107PublicMemories[stageId] ??
    mat102PublicMemories[stageId];
  if (!definition) return [];

  return [
    {
      id: `default-public-memory:${stageId}:knowledge-focus`,
      scope: 'public',
      kind: 'manual',
      status: 'active',
      source: 'manual',
      stageId,
      title: definition.title,
      text: definition.text,
      sourceReferences: [],
      createdAt:
        mat102PublicMemories[stageId] !== undefined
          ? MAT102_PUBLIC_MEMORY_UPDATED_AT
          : MAT136_PUBLIC_MEMORY_UPDATED_AT,
      updatedAt:
        mat102PublicMemories[stageId] !== undefined
          ? MAT102_PUBLIC_MEMORY_UPDATED_AT
          : MAT136_PUBLIC_MEMORY_UPDATED_AT,
    },
  ];
}

export function getDefaultCoursePublicMemories(
  course: DefaultCoursePublicMemoryInput,
): DefaultPublicMemoryItem[] {
  const definition = isMat136Course(course) ? mat136CoursePublicMemory : null;
  if (!definition) return [];

  return [
    {
      id: `default-public-memory:course:${course.id}:knowledge-map`,
      scope: 'public',
      kind: 'manual',
      status: 'active',
      source: 'manual',
      stageId: course.id,
      title: definition.title,
      text: definition.text,
      sourceReferences: [],
      createdAt: MAT136_PUBLIC_MEMORY_UPDATED_AT,
      updatedAt: MAT136_PUBLIC_MEMORY_UPDATED_AT,
    },
  ];
}

export function countDefaultCoursePublicMemories(course: DefaultCoursePublicMemoryInput): number {
  return getDefaultCoursePublicMemories(course).length;
}
