export type NewUserJourneyPriority = 'P0' | 'P1' | 'P2';

export type NewUserJourneyVerdict =
  | 'untested'
  | 'pass'
  | 'friction'
  | 'fail'
  | 'blocked'
  | 'not-applicable';

export interface NewUserJourneyCheck {
  id: string;
  title: string;
  action: string;
  expected: string;
  priority: NewUserJourneyPriority;
  href: string;
  entryLabel: string;
  boundary?: string;
}

export interface NewUserJourneyStage {
  id: string;
  order: number;
  eyebrow: string;
  title: string;
  acceptanceQuestion: string;
  description: string;
  checks: NewUserJourneyCheck[];
}

export const NEW_USER_JOURNEY_STORAGE_KEY = 'syntara:qa:new-user-journey:v1';

export const NEW_USER_JOURNEY_STAGES: NewUserJourneyStage[] = [
  {
    id: 'arrival',
    order: 1,
    eyebrow: '抵达与身份',
    title: '从陌生访客变成可继续学习的用户',
    acceptanceQuestion: '用户能否在没有说明书的情况下理解平台、完成身份流程并落到正确首页？',
    description: '使用全新浏览器资料和虚构测试邮箱，不复用已有课程、会话或本地缓存。',
    checks: [
      {
        id: 'arrival-value',
        title: '理解首页价值并找到下一步',
        action: '首次打开首页，在 10 秒内说出平台是做什么的，并找到注册与登录入口。',
        expected: '价值、适用人群和主要行动清楚；不需要先登录才能理解产品。',
        priority: 'P0',
        href: '/',
        entryLabel: '打开平台首页',
      },
      {
        id: 'register-account',
        title: '创建本地 Demo 测试身份',
        action: '使用虚构姓名和测试邮箱完成本地注册，同时观察空值、格式错误和重复提交反馈。',
        expected: '页面清楚表达这是本地 Demo 身份流程；字段、校验、提交状态和失败原因都可理解。',
        priority: 'P0',
        href: '/register',
        entryLabel: '打开注册页',
        boundary: '只使用虚构测试资料，不填写真实密码或个人信息。',
      },
      {
        id: 'login-account',
        title: '本地登录与错误恢复',
        action: '退出后用刚创建的测试邮箱重新进入，并尝试一次格式无效的输入。',
        expected: '本地邮箱身份可恢复；格式无效的输入不会清空已填内容，也不会给出含糊的系统错误。',
        priority: 'P0',
        href: '/login',
        entryLabel: '打开登录页',
      },
      {
        id: 'post-auth-landing',
        title: '登录后落到学习首页',
        action: '完成注册或登录后观察最终 URL、首屏内容和加载过程。',
        expected: '最终进入 /learn；不先跳到旧工作区，也不长时间停在“已登录”中间态。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '核对学习首页',
      },
      {
        id: 'session-boundary',
        title: '刷新、退出与身份边界',
        action: '刷新页面、退出账号，再通过浏览器返回键尝试访问刚才的用户页面。',
        expected: '刷新保留当前身份；退出后受保护状态不泄漏，返回也不会展示上一用户的数据。',
        priority: 'P0',
        href: '/profile',
        entryLabel: '从个人中心验证',
      },
    ],
  },
  {
    id: 'course-start',
    order: 2,
    eyebrow: '首页与课程起步',
    title: '从零课程状态建立第一个学习空间',
    acceptanceQuestion: '新用户能否理解首页、创建课程，并在课程与系统工具之间自由移动？',
    description: '重点观察空状态、信息架构和课程上下文，而不只检查按钮是否能点击。',
    checks: [
      {
        id: 'learn-home-orientation',
        title: '理解学习首页与系统应用',
        action: '在无课程状态检查课程区、日历、个人中心、商城、设置、通知和新建课程入口。',
        expected: '首要动作突出，系统应用可发现；Haru/背景不会遮挡按钮或抢走主要注意力。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '查看学习首页',
      },
      {
        id: 'create-course-dialog',
        title: '用弹窗创建第一门课程',
        action: '从学习首页点击新建课程，填写最少必需信息并完成创建。',
        expected: '创建发生在当前上下文的弹窗中；字段、取消、提交中和成功后的去向清楚。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '打开新建课程入口',
      },
      {
        id: 'course-purpose',
        title: '选择大学、研究或日常用途',
        action: '查看三种课程用途的说明，并分别判断后续文案、快捷建议和计划入口是否匹配。',
        expected: '用途差异面向用户而非内部枚举；研究课程不会继续使用考试或 syllabus 套话。',
        priority: 'P1',
        href: '/courses/new',
        entryLabel: '查看课程表单',
      },
      {
        id: 'all-courses',
        title: '查看与管理所有课程',
        action: '打开所有课程，识别当前课程、最近使用状态、创建入口和进入课程的方式。',
        expected: '空状态与有课程状态都可理解；课程卡片的主要行动一致且不会产生重复课程。',
        priority: 'P1',
        href: '/my-courses',
        entryLabel: '打开所有课程',
      },
      {
        id: 'course-switch',
        title: '切换课程与返回首页',
        action: '至少建立两门测试课程，在 /learn 切换课程，再返回无课程参数的学习首页。',
        expected: '切换不触发整页闪白或长时间重载；聊天、资料和记忆始终跟随正确课程。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '测试课程切换',
      },
      {
        id: 'course-owner-lifecycle',
        title: '编辑、发布与删除自建课程',
        action: '修改本轮创建的测试课程，检查发布入口，再删除其中一门不再需要的测试课程。',
        expected:
          '仅 owner 能看到管理动作；发布状态与影响明确；删除前说明资料、笔记本和进度范围并要求确认。',
        priority: 'P0',
        href: '/my-courses',
        entryLabel: '管理测试课程',
        boundary: '只删除本轮创建、确认无保留价值的测试课程。',
      },
    ],
  },
  {
    id: 'course-setup',
    order: 3,
    eyebrow: '课程资料',
    title: '把真实资料变成可用的课程上下文',
    acceptanceQuestion: '用户能否知道该上传什么、系统正在做什么，以及处理后的资料去了哪里？',
    description: '准备一份小型 PDF 或 Markdown、一份全是题目的文件，以及一个故意不支持的文件。',
    checks: [
      {
        id: 'course-home',
        title: '理解课程主页',
        action: '从课程卡片进入课程主页，识别资料库、模版库、题库、课程学习和课程状态。',
        expected: '课程上下文稳定可见；跨课程入口与当前课程入口不会混在一起。',
        priority: 'P0',
        href: '/my-courses',
        entryLabel: '从课程列表进入',
      },
      {
        id: 'source-upload',
        title: '上传课程资料',
        action: '上传一份支持的课程资料，观察文件选择、大小/类型提示和开始处理的反馈。',
        expected: '上传动作明确；文件信息可核对；重复或不支持的文件给出可恢复说明。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '在学习页上传',
      },
      {
        id: 'source-progress-error',
        title: '理解处理进度与失败状态',
        action: '等待解析、入库和后处理完成，并额外触发一次可恢复失败。',
        expected: '公开进度与最终状态一致；成功不向聊天追加噪声气泡，失败反馈持续可见。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '观察资料处理',
      },
      {
        id: 'resource-library',
        title: '在资料库找到上传结果',
        action: '从当前课程进入资料库，使用搜索、记忆、笔记本和题库四个入口查找刚才的内容。',
        expected: '搜索优先；列表—详情预览可用；同一资料不会在多个标签中变成互相矛盾的版本。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '从当前课程进入资料库',
      },
      {
        id: 'source-trace',
        title: '核对来源与知识图谱标记',
        action: '打开资料详情，检查文件名、章节、知识图谱标签和可追溯来源。',
        expected: '标签帮助检索而不是装饰；结论能回到课程内原始资料，且不暴露服务器路径。',
        priority: 'P1',
        href: '/learn',
        entryLabel: '检查课程资料',
      },
      {
        id: 'source-delete-cascade',
        title: '删除资料并核对级联影响',
        action: '删除一份本轮上传的测试资料，再搜索相关资料片段、记忆、笔记本和题目来源。',
        expected:
          '删除前说明会保留或移除什么；删除后索引与可见列表一致，不留下幽灵结果或误删独立产物。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '从课程资料库操作',
        boundary: '只删除为本轮准备的测试资料。',
      },
    ],
  },
  {
    id: 'learning-chat',
    order: 4,
    eyebrow: '学习对话',
    title: '用文字、图片和课堂模式完成一次真实学习',
    acceptanceQuestion: '聊天是否像一个会使用课程上下文的学习工作台，而不是通用聊天框？',
    description: '同一个知识点先用文字提问，再附图追问，最后选择是否生成短课堂。',
    checks: [
      {
        id: 'text-and-quick-prompt',
        title: '快捷问题与自由提问',
        action: '先点击一条符合课程用途的快捷建议，再发送一条自定义学习问题。',
        expected: '快捷建议是可编辑起点；输入、发送、停止和再次追问的状态都明确。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '开始课程对话',
      },
      {
        id: 'image-and-model',
        title: '添加图片并选择模型',
        action: '附上一张测试题截图，切换一次模型，再发送带图片的问题。',
        expected: '图片可预览、可移除且随消息真正送达；模型选择不会丢失草稿或附件。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '测试富文本输入框',
        boundary: '只上传为本次测试准备的非敏感图片。',
      },
      {
        id: 'public-progress-live2d',
        title: '等待进度与 Live2D 联动',
        action: '发送需要课程检索的问题，观察聊天等待态和右下角讲师状态。',
        expected: '只展示可公开的进度摘要；聊天与 Live2D 同步，最终答案出现后及时结束等待态。',
        priority: 'P1',
        href: '/learn',
        entryLabel: '观察回答过程',
      },
      {
        id: 'grounded-answer-history',
        title: '课程证据与会话恢复',
        action: '核对答案是否使用本课程资料，连续追问后刷新，再重新打开这段会话。',
        expected: '不知道时会说明边界；课程证据不串线；刷新后消息、附件与课堂邀请仍可访问。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '检查对话结果',
      },
      {
        id: 'mini-classroom',
        title: '主动生成并播放短课堂',
        action: '在讲解型回答后选择生成课堂，打开 1–2 页弹窗课堂并播放讲解。',
        expected: '只有用户明确选择才生成；遮罩/焦点、文字和语音同步，关闭后回到原对话。',
        priority: 'P1',
        href: '/learn',
        entryLabel: '测试课堂讲解',
      },
    ],
  },
  {
    id: 'planning-memory',
    order: 5,
    eyebrow: '计划与记忆',
    title: '让平台知道学到哪、哪里弱、下一步做什么',
    acceptanceQuestion: '计划和记忆是否可确认、可解释，并始终属于正确用户与课程？',
    description: '使用含作业和考试日期的 syllabus，并准备两个标题相似的日历事项测试歧义。',
    checks: [
      {
        id: 'syllabus-calendar-draft',
        title: '从 syllabus 生成日历草稿',
        action: '上传课程大纲并要求整理作业、考试和复习节点。',
        expected: '日期、时区、标题、类型和来源可核对；未确认前不会直接写入日历。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '从课程对话生成',
      },
      {
        id: 'calendar-confirmation',
        title: '确认后写入日历',
        action: '检查草稿差异后确认写入，再打开日历查找新事项。',
        expected: '确认动作明确且幂等；日历显示与草稿一致，刷新后仍存在。',
        priority: 'P0',
        href: '/calendar',
        entryLabel: '打开日历',
      },
      {
        id: 'calendar-natural-crud',
        title: '自然语言新增、修改与删除',
        action: '新增一个复习事项，再用“刚才那个”修改和删除，并用双候选制造一次歧义。',
        expected: '唯一目标才产生提案；所有写操作都需确认；歧义时追问且不改日历。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '用课程对话操作',
      },
      {
        id: 'learner-state-query',
        title: '询问进度、薄弱点与下一步',
        action: '依次询问“我学到哪了”“我哪里薄弱”“下一步怎么学”。',
        expected: '回答基于真实对话、资料和做题证据；区分掌握、卡点、原因和下一教学动作。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '查询学习状态',
      },
      {
        id: 'memory-course-isolation',
        title: '验证用户与课程记忆隔离',
        action: '切换到第二门课程提出同类问题，再回到第一门课程比较答案。',
        expected: '稳定个人偏好可复用；课程学习状态、资料、题目和日历证据不会跨课程串入。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '切换课程对照',
      },
      {
        id: 'milestone-and-memory-pages',
        title: '查看课程里程碑与记忆详情',
        action: '从课程主页打开里程碑和课程记忆，核对阶段目标、来源证据与更新时间。',
        expected:
          '摘要与聊天中的学习状态一致；精确事实、近期状态和长期判断不会互相覆盖或显示内部字段。',
        priority: 'P1',
        href: '/my-courses',
        entryLabel: '从课程主页进入',
      },
    ],
  },
  {
    id: 'notebook-practice',
    order: 6,
    eyebrow: '笔记本与练习',
    title: '从资料产物走到做题、反馈和复习',
    acceptanceQuestion: '内容生成、题库练习和学习进度能否形成可返回、可恢复的闭环？',
    description: '优先使用测试课程内的短资料和已有题库，避免无目的地产生昂贵内容。',
    checks: [
      {
        id: 'creator-workbench',
        title: '使用创作者工作台',
        action: '上传小型资料，查看 AI 自动路由、手动生成路径、历史和失败恢复。',
        expected: '课程型、研究型与视觉型产物边界清楚；运行历史可重开且不会写错课程。',
        priority: 'P1',
        href: '/creator',
        entryLabel: '打开创作者',
      },
      {
        id: 'course-notebook-create',
        title: '在课程内创建或导入笔记本',
        action: '从当前课程进入创建笔记本流程，尝试文本/Markdown 路径并取消一次。',
        expected: '课程归属、来源、生成方式和消耗动作在提交前可见；取消不会留下半成品。',
        priority: 'P0',
        href: '/my-courses',
        entryLabel: '从课程进入',
      },
      {
        id: 'image-notebook-generation',
        title: '完整生成图片笔记本',
        action: '用短资料触发一次图片笔记本生成，观察结构规划、逐页进度、封面和最终页。',
        expected: '消耗型动作在开始前可确认；页面职责、图中文字、失败重试和最终笔记本归属都清楚。',
        priority: 'P1',
        href: '/creator',
        entryLabel: '生成测试图片笔记本',
      },
      {
        id: 'notebook-reader-classroom',
        title: '阅读笔记本并进入课堂',
        action: '打开生成或导入的笔记本，检查目录、正文、图像、课堂入口和返回路径。',
        expected: '长内容可导航；文本与图片不截断；课堂结束后能回到原笔记本位置。',
        priority: 'P1',
        href: '/my-courses',
        entryLabel: '打开课程内容',
      },
      {
        id: 'classroom-tools',
        title: '使用课堂讲义、追问、语音、白板与编辑',
        action: '进入一份测试课堂，逐项打开讲义/任务侧栏、追问、语音、白板或标注和可用的编辑入口。',
        expected:
          '播放与编辑职责不混淆；遮罩、语音和页面同步；退出课堂后改动、进度和返回位置可恢复。',
        priority: 'P1',
        href: '/my-courses',
        entryLabel: '从测试笔记本进入课堂',
      },
      {
        id: 'template-library',
        title: '浏览课程模版库',
        action: '从当前课程进入模版库，查看模版用途、预览和应用入口。',
        expected: '模版是一级可发现能力；用户能在应用前理解它会生成或修改什么。',
        priority: 'P2',
        href: '/learn',
        entryLabel: '从当前课程进入模版库',
      },
      {
        id: 'problem-bank-navigation',
        title: '从笔记本进入过滤后的题库',
        action: '点击笔记本卡片上的题目数量，再使用课程题库的搜索、筛选和题目详情。',
        expected: '题目数量是可点击的导航；过滤条件正确保留，题面、难度、标签和来源可核对。',
        priority: 'P0',
        href: '/my-courses',
        entryLabel: '从笔记本卡片开始',
      },
      {
        id: 'practice-submit-review',
        title: '作答、反馈、练习计划与复习',
        action: '提交一题，查看判定与讲解，再进入练习计划/复习页并刷新。',
        expected: '提交状态与分数清楚；反馈引用真实题目；进度、最新作答和记忆更新跨刷新一致。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '从课程题库开始',
      },
    ],
  },
  {
    id: 'marketplace',
    order: 7,
    eyebrow: '商城与积分',
    title: '发现内容并理解每一次有成本的操作',
    acceptanceQuestion: '新用户能否分清课程、笔记本、形象和积分，并在付费前获得充分信息？',
    description: '本轮只走到最终确认前；不进行真实支付、充值或不可逆购买。',
    checks: [
      {
        id: 'course-store',
        title: '浏览与搜索课程商城',
        action: '进入课程商城，使用分类或搜索打开一门课程详情。',
        expected: '课程价值、作者、内容范围、价格/权益和进入方式清楚；空结果可恢复。',
        priority: 'P1',
        href: '/store/courses',
        entryLabel: '打开课程商城',
      },
      {
        id: 'course-enrollment-gate',
        title: '检查加入或购买课程的确认边界',
        action: '选择一门测试课程，走到加入/购买的最终确认前并核对余额变化说明。',
        expected: '免费、购买、余额不足和已拥有状态可区分；最终动作前清楚显示成本与结果。',
        priority: 'P0',
        href: '/store/courses',
        entryLabel: '检查课程详情',
        boundary: '不要确认真实付费；测试到最终确认前即止。',
      },
      {
        id: 'course-review',
        title: '完成课程后查看评价入口',
        action: '在已加入的测试课程详情或学习进度中寻找评分/评价入口，检查提交与重复评价规则。',
        expected: '只有符合条件的用户可评价；评分、文字和公开范围明确，提交前可取消。',
        priority: 'P2',
        href: '/store/courses',
        entryLabel: '从课程详情检查',
        boundary: '只对免费或已准备的测试课程提交；否则标记不适用，不要真实消费。',
      },
      {
        id: 'notebook-store',
        title: '浏览当前课程的笔记本商城',
        action: '先选择课程，再打开笔记本商城，检查内容是否限定在正确课程上下文。',
        expected: '课程商城与笔记本商城不混淆；离开课程后不会继续显示错误的课程商品。',
        priority: 'P1',
        href: '/store',
        entryLabel: '打开笔记本商城',
      },
      {
        id: 'avatar-store',
        title: '浏览抽卡补给站',
        action: '查看讲师形象、稀有度、价格/概率说明和拥有状态，走到确认前。',
        expected: '展示内容与实际可装备形象一致；抽取或购买前有明确成本与确认。',
        priority: 'P1',
        href: '/store/avatars',
        entryLabel: '打开抽卡补给站',
        boundary: '不要执行不可逆抽取或购买。',
      },
      {
        id: 'credits-center',
        title: '理解充值、转换与交易积分',
        action: '分别打开充值/转换和交易积分页面，核对三类余额、汇率、手续费和确认文案。',
        expected: '现金、算力、购买积分不混用；无余额或不可交易时给出下一步而不是死按钮。',
        priority: 'P0',
        href: '/top-up',
        entryLabel: '打开充值/转换',
        boundary: '不提交真实充值、支付或市场交易。',
      },
    ],
  },
  {
    id: 'personal-system',
    order: 8,
    eyebrow: '个人与系统',
    title: '完成个性化、通知和跨应用协作',
    acceptanceQuestion: '个人信息和系统偏好是否可发现、可修改，并在不同页面保持一致？',
    description: '只修改测试账号的非敏感资料；外部客服与问题上报只验证入口，不实际发送。',
    checks: [
      {
        id: 'profile-center',
        title: '查看与编辑个人中心',
        action: '点击头像进入个人中心，修改测试昵称或简介并刷新。',
        expected: '头像直接进入 /profile；页面没有课程侧栏；保存反馈和跨页面展示一致。',
        priority: 'P1',
        href: '/profile',
        entryLabel: '打开个人中心',
      },
      {
        id: 'profile-appearance',
        title: '选择头像并预览头像框',
        action: '选择一个已拥有头像，预览锁定头像框，并在有可用头像框时应用后刷新。',
        expected:
          '已拥有、未解锁和当前使用状态清楚；锁定是预期门槛，应用后的装扮在全局壳层保持一致。',
        priority: 'P1',
        href: '/profile',
        entryLabel: '检查头像与头像框',
      },
      {
        id: 'profile-usage',
        title: '核对成长、积分与 Token 使用量',
        action: '在个人中心和侧栏对照成长等级、现金/算力/购买积分，并切换 Credits 与 Token 明细。',
        expected: '各页面数值一致；分页、空状态和刷新可理解；未加载或余额为零不会伪装成错误余额。',
        priority: 'P2',
        href: '/profile',
        entryLabel: '检查账号用量',
      },
      {
        id: 'settings',
        title: '调整语言、主题、背景和模型设置',
        action: '切换中英文、深浅主题和学习首页背景，并查看模型/服务提供者设置。',
        expected: '设置即时或明确保存；不同页面保持一致；缺少 API 配置时给出可行动说明。',
        priority: 'P1',
        href: '/settings',
        entryLabel: '打开设置',
      },
      {
        id: 'live2d-center',
        title: '管理讲师形象与使用场景',
        action: '进入讲师中心，查看课堂、通知和签到等形象设置及预览。',
        expected: '选择结果与课程等待态/课堂中的形象一致；预览不遮挡主要控制。',
        priority: 'P2',
        href: '/live2d',
        entryLabel: '打开讲师中心',
      },
      {
        id: 'notifications',
        title: '查看、标记与跳转通知',
        action: '打开通知中心，检查未读计数、已读操作、目标跳转和空状态。',
        expected: '计数与列表一致；点击后进入正确课程/任务；重复打开不会制造重复通知。',
        priority: 'P1',
        href: '/notifications',
        entryLabel: '打开通知中心',
      },
      {
        id: 'legacy-chat-redirect',
        title: '验证旧聊天入口的兼容跳转',
        action: '直接打开 /chat，观察最终 URL、加载过程和是否保留当前课程上下文。',
        expected: '旧入口稳定进入 /learn，不出现旧聊天壳层、循环跳转或丢失可恢复上下文。',
        priority: 'P2',
        href: '/chat',
        entryLabel: '打开旧聊天入口',
      },
      {
        id: 'agent-team',
        title: '浏览 Agent 团队入口',
        action: '从无课程上下文进入 Agent 团队，查看团队职责、可用操作和进入课程协作的方式。',
        expected: '团队与课程学习对话职责清楚；进入或退出不会意外创建课程或丢失当前课程。',
        priority: 'P2',
        href: '/agent-teams',
        entryLabel: '打开 Agent 团队',
      },
    ],
  },
  {
    id: 'recovery',
    order: 9,
    eyebrow: '恢复与发布门槛',
    title: '证明旅程在失败、刷新和重新登录后仍然成立',
    acceptanceQuestion: '当网络、模型、文件或用户操作出错时，平台能否保护数据并引导继续？',
    description: '最后统一复查跨页面状态、错误恢复、确认边界和帮助入口，再给出发布判定。',
    checks: [
      {
        id: 'refresh-persistence',
        title: '跨刷新恢复关键产物',
        action: '刷新课程、对话、日历、笔记本、题库进度和本测试页。',
        expected: '已确认的业务数据与本地测试记录都能恢复；临时草稿是否保留有清晰规则。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '从学习页复查',
      },
      {
        id: 'navigation-context',
        title: '验证返回、前进与深链接',
        action: '使用浏览器返回/前进，并直接打开一个课程内深链接。',
        expected: '不会落入错误课程、空白页或无限跳转；当前课程和顶部/侧边导航同步。',
        priority: 'P0',
        href: '/my-courses',
        entryLabel: '从课程入口复查',
      },
      {
        id: 'runtime-failure-recovery',
        title: '恢复上传、生成与模型失败',
        action: '制造一次文件失败和一次不可用模型/网络失败，然后使用页面提供的恢复动作。',
        expected: '已有输入与已完成产物不丢失；错误可理解、可重试，也不暴露内部堆栈或密钥。',
        priority: 'P0',
        href: '/learn',
        entryLabel: '测试错误恢复',
      },
      {
        id: 'confirmation-safety',
        title: '复查写入、删除与成本确认',
        action: '抽查日历删除、课程/内容购买、积分操作和覆盖性保存的最终一步。',
        expected: '目标、影响和成本明确；歧义或重复提交不会产生不可逆副作用。',
        priority: 'P0',
        href: '/calendar',
        entryLabel: '抽查确认边界',
        boundary: '只对本次创建的测试数据执行删除；不确认真实支付。',
      },
      {
        id: 'relogin-support',
        title: '重新登录并找到帮助',
        action: '退出再登录测试账号，核对课程/进度恢复，并打开联系客服与报告问题入口。',
        expected: '账号数据完整恢复；帮助入口可发现且能携带必要上下文，但不会未经确认自动发送。',
        priority: 'P0',
        href: '/login',
        entryLabel: '重新登录复查',
      },
    ],
  },
];

export const NEW_USER_JOURNEY_CHECKS = NEW_USER_JOURNEY_STAGES.flatMap((stage) => stage.checks);
