import type { AgentSkillDefinition, AgentToolDefinition } from '@/features/agent/domain/types';

export const REVIEW_AGENT_TOOLS = [
  {
    id: 'assess_problem_bank',
    namespace: 'openmaic.review',
    feature: 'review',
    title: 'Assess problem bank',
    description:
      'Judge whether the available problem bank and memory are enough for a custom route.',
    status: 'route-backed',
    inputContract:
      'Notebook/course context, scenes, problem-bank summary, memory, and review history.',
    outputContract: 'Readiness assessment, missing/thin concepts, and teacher-facing reason line.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/review-route/assess-problem-bank' }],
    sideEffects: ['llm'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'generate_review_route',
    namespace: 'openmaic.review',
    feature: 'review',
    title: 'Generate review route',
    description:
      'Build a personalized review map from weak points, candidate problems, and memory.',
    status: 'route-backed',
    inputContract:
      'Notebook/course context, weak points, scenes, candidate problems, memory, and history.',
    outputContract: 'Validated ReviewRoute with layers, nodes, problem ids, and pass criteria.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/review-route/generate' }],
    sideEffects: ['llm'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'grade_answer',
    namespace: 'openmaic.review',
    feature: 'practice',
    title: 'Grade answer',
    description: 'Grade a short-answer, proof, or tracing response against reference material.',
    status: 'route-backed',
    inputContract:
      'Question, user answer, points, question type, and reference answer/proof/analysis.',
    outputContract: 'Score and feedback comment.',
    entrypoints: [
      { kind: 'route', method: 'POST', ref: '/api/quiz-grade' },
      { kind: 'service', ref: '@/features/practice/server/grade-answer#gradeQuizAnswer' },
    ],
    sideEffects: ['llm'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'run_code_answer',
    namespace: 'openmaic.review',
    feature: 'practice',
    title: 'Run code answer',
    description: 'Execute or validate code-answer questions in the controlled quiz runner.',
    status: 'route-backed',
    inputContract: 'Code question payload, submitted code, runtime, and test cases.',
    outputContract: 'Execution report and grading support payload.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/quiz-code-run' }],
    sideEffects: ['long-running-job'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'record_problem_attempt',
    namespace: 'openmaic.review',
    feature: 'problems',
    title: 'Record problem attempt',
    description: 'Persist a problem-bank attempt and update per-user progress.',
    status: 'route-backed',
    inputContract: 'Notebook id, problem id, attempt answer, grading result, score, and status.',
    outputContract: 'NotebookProblemAttempt and updated NotebookProblemProgress.',
    entrypoints: [
      { kind: 'route', method: 'POST', ref: '/api/notebooks/[id]/problems/[problemId]/attempts' },
    ],
    sideEffects: ['database-write'],
    requiresAuth: true,
    requiresDatabase: true,
  },
] satisfies readonly AgentToolDefinition[];

export const CUSTOM_REVIEW_ROUTE_SKILL = {
  id: 'custom_review_route',
  title: 'Custom review route',
  primaryUserFunction: 'Custom review',
  description:
    'Create and run a personalized review route using course content, problem progress, private memory, and grading feedback.',
  skillDocumentPath: 'features/agent/skills/custom-review/SKILL.md',
  skillDocumentUri: 'openmaic://skills/custom_review_route',
  supportingSkillDocumentIds: [],
  mcpNamespaces: [
    'openmaic.content',
    'openmaic.problem_bank',
    'openmaic.review',
    'openmaic.memory',
  ],
  toolIds: [
    'read_notebook_context',
    'list_problem_bank',
    'list_study_memory',
    'assess_problem_bank',
    'generate_review_route',
    'grade_answer',
    'run_code_answer',
    'record_problem_attempt',
    'create_study_memory',
  ],
  stages: [
    {
      id: 'profile',
      title: 'Build learner profile',
      description: 'Read notebook scenes, problem progress, private memory, and review history.',
      toolIds: ['read_notebook_context', 'list_problem_bank', 'list_study_memory'],
      required: true,
    },
    {
      id: 'readiness',
      title: 'Assess readiness',
      description: 'Check whether enough problems exist for a useful review route.',
      toolIds: ['assess_problem_bank'],
      required: true,
    },
    {
      id: 'route',
      title: 'Generate route',
      description: 'Create the review map and bind nodes to candidate problems.',
      toolIds: ['generate_review_route'],
      required: true,
    },
    {
      id: 'practice',
      title: 'Practice and grade',
      description: 'Grade answers, run code when needed, and persist attempts.',
      toolIds: ['grade_answer', 'run_code_answer', 'record_problem_attempt'],
      required: true,
    },
    {
      id: 'memory',
      title: 'Write private memory',
      description: 'Capture recurring mistakes or preferences as private study memory.',
      toolIds: ['create_study_memory'],
      required: false,
    },
  ],
  qualityGates: [
    'Review route uses real problem progress rather than only slide quiz state.',
    'Problem-bank readiness is explicit before route generation.',
    'Attempt persistence updates NotebookProblemProgress for future personalization.',
    'New memory is private by default unless a creator intentionally writes public memory.',
  ],
  outputs: ['ReviewRoute', 'Problem attempts/progress', 'Optional private study memory'],
} satisfies AgentSkillDefinition;
