import type { AgentSkillDefinition, AgentToolDefinition } from '@/features/agent/domain/types';

export const MEMORY_AGENT_TOOLS = [
  {
    id: 'list_memory_facts',
    namespace: 'openmaic.memory',
    feature: 'memory',
    title: 'List structured memory facts',
    description:
      'Read exact active or historical structured memory facts for a user, course, notebook, or conversation scope.',
    status: 'route-backed',
    inputContract: 'scopeType, scopeId, namespace, key, includeSuperseded, and limit.',
    outputContract: 'MemoryFactRecord list and storage backend indicator.',
    entrypoints: [{ kind: 'route', method: 'GET', ref: '/api/memory/facts' }],
    sideEffects: ['database-read'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'upsert_memory_fact',
    namespace: 'openmaic.memory',
    feature: 'memory',
    title: 'Upsert structured memory fact',
    description:
      'Write the current value for a key fact, superseding the old active value and recording a fact event.',
    status: 'route-backed',
    inputContract:
      'scopeType, scopeId, namespace, key, valueJson, confidence, source, and sourceRef.',
    outputContract: 'Current MemoryFactRecord and MemoryFactEventRecord.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/memory/facts' }],
    sideEffects: ['database-write'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'get_layered_memory_context',
    namespace: 'openmaic.memory',
    feature: 'memory',
    title: 'Get layered memory context',
    description:
      'Build the chat recall context with control facts, short-term state, long-term text memory, knowledge cache, and knowledge-base RAG separated.',
    status: 'route-backed',
    inputContract: 'targetType, targetId, message, and optional conversationId.',
    outputContract:
      'Prompt plus readPlan, layers, staticFacts, directMemories, semanticMatches, knowledgeCache, knowledgeMatches, learnerAnalytics, conflicts, and counts.',
    entrypoints: [{ kind: 'route', method: 'GET', ref: '/api/memory/context' }],
    sideEffects: ['database-read'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'plan_memory_source_ingestion',
    namespace: 'openmaic.memory',
    feature: 'memory',
    title: 'Plan source memory ingestion',
    description:
      'Convert an uploaded creator/learner source into memory artifacts: long-term template candidates, knowledge-base source candidates, and discarded generic concepts.',
    status: 'route-backed',
    inputContract:
      'sourceTitle, text, sourceKind, audience, optional targetType, targetId, and courseCode.',
    outputContract:
      'SourceMemoryIngestionPlan with artifacts, writeCandidates, layer assignments, and token policy.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/memory/ingest/plan' }],
    sideEffects: ['none'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'list_study_memory',
    namespace: 'openmaic.memory',
    feature: 'memory',
    title: 'List study memory',
    description: 'Read visible public/private study memories for a course or notebook target.',
    status: 'route-backed',
    inputContract: 'targetType and targetId.',
    outputContract: 'StudyMemoryRecord list and storage backend indicator.',
    entrypoints: [{ kind: 'route', method: 'GET', ref: '/api/study-memory' }],
    sideEffects: ['database-read'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'create_study_memory',
    namespace: 'openmaic.memory',
    feature: 'memory',
    title: 'Create study memory',
    description: 'Write a public or private memory entry to a course or notebook target.',
    status: 'route-backed',
    inputContract:
      'targetType, targetId, scope, kind, source, title, text, reason, question, and references.',
    outputContract: 'Created StudyMemoryRecord.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/study-memory' }],
    sideEffects: ['database-write'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'update_study_memory_status',
    namespace: 'openmaic.memory',
    feature: 'memory',
    title: 'Update study memory status',
    description: 'Archive or reactivate a study memory owned by the current user.',
    status: 'route-backed',
    inputContract: 'memoryId and status.',
    outputContract: 'Updated StudyMemoryRecord.',
    entrypoints: [{ kind: 'route', method: 'PATCH', ref: '/api/study-memory/[id]' }],
    sideEffects: ['database-write'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'delete_study_memory',
    namespace: 'openmaic.memory',
    feature: 'memory',
    title: 'Delete study memory',
    description: 'Delete a study memory owned by the current user.',
    status: 'route-backed',
    inputContract: 'memoryId.',
    outputContract: 'Deletion result.',
    entrypoints: [{ kind: 'route', method: 'DELETE', ref: '/api/study-memory/[id]' }],
    sideEffects: ['database-write'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'write_local_study_memory',
    namespace: 'openmaic.memory',
    feature: 'memory',
    title: 'Write local study memory',
    description: 'Write local-first memory when the database-backed API is unavailable.',
    status: 'client-backed',
    inputContract: 'stageId, userId, scope, kind, title, text, and optional source metadata.',
    outputContract: 'Updated local StudyMemoryProfile and created memory item.',
    entrypoints: [{ kind: 'client', ref: '@/lib/learning/study-memory' }],
    sideEffects: ['local-storage'],
    requiresAuth: false,
    requiresDatabase: false,
  },
] satisfies readonly AgentToolDefinition[];

export const INGEST_SOURCE_MEMORY_SKILL = {
  id: 'ingest_source_memory',
  title: 'Ingest source into memory',
  primaryUserFunction: 'Import memory',
  description:
    'Plan how an uploaded course file, template library, or learner source becomes public long-term memory, private learner memory, and RAG knowledge.',
  skillDocumentPath: 'features/agent/skills/ingest-source-memory/SKILL.md',
  skillDocumentUri: 'openmaic://skills/ingest_source_memory',
  supportingSkillDocumentIds: [],
  mcpNamespaces: ['openmaic.content', 'openmaic.memory', 'openmaic.problem_bank'],
  toolIds: [
    'read_course_context',
    'read_notebook_context',
    'plan_memory_source_ingestion',
    'create_study_memory',
    'upsert_memory_fact',
    'preview_problem_import',
    'commit_problem_import',
  ],
  stages: [
    {
      id: 'target',
      title: 'Resolve owner and target',
      description:
        'Identify course/notebook target and whether the uploader is creator or learner.',
      toolIds: ['read_course_context', 'read_notebook_context'],
      required: true,
    },
    {
      id: 'plan',
      title: 'Plan memory artifacts',
      description:
        'Classify the source into long-term text memory, knowledge-base RAG, problem bank, or ignored generic concept.',
      toolIds: ['plan_memory_source_ingestion'],
      required: true,
    },
    {
      id: 'commit',
      title: 'Commit approved writes',
      description:
        'Write approved text memories, structured facts, or problem-bank imports through their owning tools.',
      toolIds: [
        'create_study_memory',
        'upsert_memory_fact',
        'preview_problem_import',
        'commit_problem_import',
      ],
      required: false,
    },
  ],
  qualityGates: [
    'Promote only course-local contracts, templates, invariants, forbidden moves, and grading checks into long-term memory.',
    'Keep full source files and large problem sets in knowledge-base RAG instead of static memory.',
    'Do not store generic definitions such as "what is a class" unless the teacher source changes how the answer must be written.',
    'Creator uploads may create public course/notebook memory; learner uploads default to private memory.',
    'Every committed artifact must keep sourceTitle/sourceKind/sourceRef for later auditing.',
  ],
  outputs: ['SourceMemoryIngestionPlan and approved MemoryWriteCandidate records'],
} satisfies AgentSkillDefinition;

export const WRITE_STUDY_MEMORY_SKILL = {
  id: 'write_study_memory',
  title: 'Write study memory',
  primaryUserFunction: 'Write memory',
  description:
    'Capture public course/notebook study notes or private learner experiences that are useful as text memory.',
  skillDocumentPath: 'features/agent/skills/write-memory/SKILL.md',
  skillDocumentUri: 'openmaic://skills/write_study_memory',
  supportingSkillDocumentIds: [],
  mcpNamespaces: ['openmaic.content', 'openmaic.memory'],
  toolIds: [
    'read_course_context',
    'read_notebook_context',
    'list_study_memory',
    'create_study_memory',
    'update_study_memory_status',
    'delete_study_memory',
    'write_local_study_memory',
  ],
  stages: [
    {
      id: 'target',
      title: 'Resolve target and scope',
      description: 'Identify course/notebook target and whether the memory is public or private.',
      toolIds: ['read_course_context', 'read_notebook_context'],
      required: true,
    },
    {
      id: 'dedupe',
      title: 'Compare existing memory',
      description: 'Read existing memory to avoid duplicate or conflicting entries.',
      toolIds: ['list_study_memory'],
      required: true,
    },
    {
      id: 'write',
      title: 'Write memory',
      description: 'Persist the new memory through database-backed or local-first storage.',
      toolIds: ['create_study_memory', 'write_local_study_memory'],
      required: true,
    },
    {
      id: 'curate',
      title: 'Curate memory',
      description: 'Archive or delete stale memory when later evidence supersedes it.',
      toolIds: ['update_study_memory_status', 'delete_study_memory'],
      required: false,
    },
  ],
  qualityGates: [
    'Do not use study memory for exact overwriteable facts such as budget, language preference, identity labels, time zone, or current learning goal; use structured facts instead.',
    'Public memory writes require creator/owner access.',
    'Private memory stays per user and is never published with shared course content.',
    'Memory includes source, reason, or references when the agent inferred it.',
    'Local-first fallback is explicit and does not pretend to sync to shared course state.',
  ],
  outputs: ['StudyMemoryRecord or local StudyMemoryProfile item'],
} satisfies AgentSkillDefinition;

export const WRITE_FACT_MEMORY_SKILL = {
  id: 'write_fact_memory',
  title: 'Write structured fact memory',
  primaryUserFunction: 'Write memory',
  description:
    'Capture exact current facts such as profile attributes, preferences, budget, time zone, course constraints, and current goals with overwrite semantics.',
  skillDocumentPath: 'features/agent/skills/write-fact-memory/SKILL.md',
  skillDocumentUri: 'openmaic://skills/write_fact_memory',
  supportingSkillDocumentIds: [],
  mcpNamespaces: ['openmaic.content', 'openmaic.memory'],
  toolIds: [
    'read_course_context',
    'read_notebook_context',
    'list_memory_facts',
    'upsert_memory_fact',
    'get_layered_memory_context',
  ],
  stages: [
    {
      id: 'target',
      title: 'Resolve exact fact scope',
      description: 'Choose the narrowest correct scope: user, course, notebook, or conversation.',
      toolIds: ['read_course_context', 'read_notebook_context'],
      required: true,
    },
    {
      id: 'read-current',
      title: 'Read current fact',
      description: 'Check for the active value before overwriting it.',
      toolIds: ['list_memory_facts'],
      required: true,
    },
    {
      id: 'upsert',
      title: 'Upsert current fact',
      description: 'Write the current value; the old active value is superseded automatically.',
      toolIds: ['upsert_memory_fact'],
      required: true,
    },
  ],
  qualityGates: [
    'Use structured facts for precise, controllable, or updateable values.',
    'Use the narrowest scope that matches the user statement.',
    'Never add a second active fact with the same namespace/key/scope.',
    'Keep sourceRef when the fact came from a conversation, file, problem, or notebook.',
  ],
  outputs: ['MemoryFactRecord and MemoryFactEventRecord'],
} satisfies AgentSkillDefinition;
