import type { AgentSkillDefinition, AgentToolDefinition } from '@/features/agent/domain/types';

export const PPT_GENERATION_AGENT_TOOLS = [
  {
    id: 'generate_scene_outlines',
    namespace: 'openmaic.generation_jobs',
    feature: 'ppt-generation',
    title: 'Generate scene outlines',
    description:
      'Turn requirements and source material into a streamed notebook/PPT teaching outline.',
    status: 'route-backed',
    inputContract:
      'Requirements, course context, source text/images, agents, and generation preferences.',
    outputContract: 'Ordered SceneOutline records with teaching roles and quality metadata.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/generate/scene-outlines-stream' }],
    sideEffects: ['llm', 'long-running-job'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'generate_notebook_page_content',
    namespace: 'openmaic.generation_jobs',
    feature: 'ppt-generation',
    title: 'Generate notebook page content',
    description: 'Create page-level educational content from approved outlines.',
    status: 'route-backed',
    inputContract:
      'Scene outline, source context, course context, and neighboring page continuity.',
    outputContract: 'Validated page content payload for image or markdown notebooks.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/generate/notebook-page-content' }],
    sideEffects: ['llm'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'generate_scene_content',
    namespace: 'openmaic.generation_jobs',
    feature: 'ppt-generation',
    title: 'Generate scene content',
    description: 'Generate slide scene JSON from an outline and lesson context.',
    status: 'route-backed',
    inputContract: 'Scene outline, lesson context, style constraints, and source material.',
    outputContract: 'Scene content JSON ready for rendering or persistence.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/generate/scene-content' }],
    sideEffects: ['llm'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'generate_scene_actions',
    namespace: 'openmaic.generation_jobs',
    feature: 'ppt-generation',
    title: 'Generate scene actions',
    description: 'Generate classroom narration and action timing for a scene.',
    status: 'route-backed',
    inputContract: 'Scene content, outline, teacher persona, language, and action constraints.',
    outputContract: 'Validated scene action timeline and narration payload.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/generate/scene-actions' }],
    sideEffects: ['llm'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'generate_html_ppt_slide',
    namespace: 'openmaic.generation_jobs',
    feature: 'ppt-generation',
    title: 'Generate HTML PPT slide',
    description: 'Generate or repair a renderable HTML slide from page content.',
    status: 'route-backed',
    inputContract:
      'Page content, visual direction, layout constraints, and optional repair context.',
    outputContract: 'HTML slide document, quality risks, and asset references.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/generate/html-ppt-slide' }],
    sideEffects: ['llm'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'generate_image_asset',
    namespace: 'openmaic.asset',
    feature: 'ppt-generation',
    title: 'Generate image asset',
    description: 'Generate or transform an image asset for notebook pages.',
    status: 'route-backed',
    inputContract: 'Image prompt, provider settings, stage id, and optional reference assets.',
    outputContract: 'Generated image URL/path, provider metadata, and request usage.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/generate/image' }],
    sideEffects: ['asset-write', 'long-running-job'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'generate_tts_asset',
    namespace: 'openmaic.asset',
    feature: 'ppt-generation',
    title: 'Generate TTS asset',
    description: 'Generate speech audio for scene narration.',
    status: 'route-backed',
    inputContract: 'Narration text, voice id, speed, and target notebook/scene metadata.',
    outputContract: 'Audio asset URL/path and speech generation metadata.',
    entrypoints: [{ kind: 'route', method: 'POST', ref: '/api/generate/tts' }],
    sideEffects: ['asset-write'],
    requiresAuth: true,
    requiresDatabase: false,
  },
  {
    id: 'export_pptx',
    namespace: 'openmaic.asset',
    feature: 'ppt-generation',
    title: 'Export PPTX',
    description: 'Export the current notebook slide state to a PowerPoint file.',
    status: 'client-backed',
    inputContract: 'Stage/notebook slide model and export options.',
    outputContract: 'PPTX blob or downloaded file.',
    entrypoints: [{ kind: 'client', ref: '@/lib/export/use-export-pptx' }],
    sideEffects: ['asset-write'],
    requiresAuth: false,
    requiresDatabase: false,
  },
] satisfies readonly AgentToolDefinition[];

export const GENERATE_PPT_NOTEBOOK_SKILL = {
  id: 'generate_ppt_notebook',
  title: 'Generate PPT notebook',
  primaryUserFunction: 'Generate PPT',
  description:
    'Build a complete notebook/PPT from requirements and source material, then persist pages, actions, assets, and shared memory.',
  skillDocumentPath: 'features/agent/skills/generate-ppt/SKILL.md',
  skillDocumentUri: 'openmaic://skills/generate_ppt_notebook',
  supportingSkillDocumentIds: ['generate_ppt_page_content', 'render_lecture_image'],
  mcpNamespaces: [
    'openmaic.content',
    'openmaic.generation_jobs',
    'openmaic.asset',
    'openmaic.memory',
  ],
  toolIds: [
    'read_course_context',
    'create_generation_job',
    'generate_scene_outlines',
    'create_study_memory',
    'generate_notebook_page_content',
    'generate_scene_content',
    'generate_html_ppt_slide',
    'generate_image_asset',
    'generate_scene_actions',
    'generate_tts_asset',
    'write_notebook_scenes',
    'sync_notebook_generation',
    'export_pptx',
  ],
  stages: [
    {
      id: 'context',
      title: 'Load context',
      description:
        'Read course/notebook context, requirements, existing public memory, and source files.',
      toolIds: ['read_course_context', 'read_notebook_context'],
      required: true,
    },
    {
      id: 'outline',
      title: 'Plan teaching outline',
      description: 'Generate and validate the course spine before page generation starts.',
      toolIds: ['create_generation_job', 'generate_scene_outlines'],
      required: true,
    },
    {
      id: 'public_memory',
      title: 'Write public memory',
      description: 'Persist reusable course/notebook facts before expensive page generation.',
      toolIds: ['create_study_memory'],
      required: true,
    },
    {
      id: 'pages',
      title: 'Generate pages and actions',
      description: 'Generate page content, visual assets, classroom actions, and optional speech.',
      toolIds: [
        'generate_notebook_page_content',
        'generate_scene_content',
        'generate_html_ppt_slide',
        'generate_image_asset',
        'generate_scene_actions',
        'generate_tts_asset',
      ],
      required: true,
    },
    {
      id: 'persist',
      title: 'Persist and export',
      description: 'Write notebook content, refresh summaries, and optionally export a PPTX.',
      toolIds: ['write_notebook_scenes', 'sync_notebook_generation', 'export_pptx'],
      required: true,
    },
  ],
  qualityGates: [
    'Outline follows the source-material contract and does not leak metadata noise into lesson content.',
    'Generated page count, worked-example density, and quiz placement satisfy the selected generation preferences.',
    'Public memory is persisted before page generation so later failures do not drop shared context.',
    'Persisted notebook summaries avoid large Scene.content reads on lightweight course surfaces.',
  ],
  outputs: ['Notebook/PPT pages', 'Classroom scenes/actions', 'Generated assets', 'Public memory'],
} satisfies AgentSkillDefinition;
