import type { AgentSkillDefinition, AgentToolDefinition } from '@/features/agent/domain/types';

export const PROBLEM_BANK_AGENT_TOOLS = [
  {
    id: 'list_problem_bank',
    namespace: 'openmaic.problem_bank',
    feature: 'problems',
    title: 'List problem bank',
    description: 'Read course or notebook problem-bank records with user progress summaries.',
    status: 'route-backed',
    inputContract: 'courseId or notebookId, optional summary/filter parameters.',
    outputContract: 'Problem summaries or full problem records with latest attempt data.',
    entrypoints: [
      { kind: 'route', method: 'GET', ref: '/api/notebooks/[id]/problems' },
      { kind: 'route', method: 'GET', ref: '/api/courses/[id]/problems' },
    ],
    sideEffects: ['database-read'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'preview_problem_import',
    namespace: 'openmaic.problem_bank',
    feature: 'problems',
    title: 'Preview problem import',
    description:
      'Parse a source file/text and return normalized problem drafts before persistence.',
    status: 'route-backed',
    inputContract:
      'Notebook id, one source file or text block, import language, and parsing options.',
    outputContract: 'Problem import drafts, quality report, warnings, usage, and import batch id.',
    entrypoints: [
      { kind: 'route', method: 'POST', ref: '/api/notebooks/[id]/problems/import-preview' },
    ],
    sideEffects: ['llm', 'database-write'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'commit_problem_import',
    namespace: 'openmaic.problem_bank',
    feature: 'problems',
    title: 'Commit problem import',
    description: 'Commit reviewed import drafts to a notebook problem bank.',
    status: 'route-backed',
    inputContract: 'Notebook id, import batch id, selected drafts, and commit options.',
    outputContract: 'Created problem records and committed import-batch counters.',
    entrypoints: [
      { kind: 'route', method: 'POST', ref: '/api/notebooks/[id]/problems/import-commit' },
    ],
    sideEffects: ['database-write'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'create_problem_from_draft',
    namespace: 'openmaic.problem_bank',
    feature: 'problems',
    title: 'Create problem from draft',
    description: 'Create review problems directly from normalized drafts without the upload flow.',
    status: 'route-backed',
    inputContract: 'Notebook id or course id plus NotebookProblemImportDraft records.',
    outputContract: 'Created problem records.',
    entrypoints: [
      { kind: 'route', method: 'POST', ref: '/api/notebooks/[id]/problems' },
      {
        kind: 'service',
        ref: '@/features/problems/server/service#createNotebookProblemsFromDrafts',
      },
    ],
    sideEffects: ['database-write'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'update_problem',
    namespace: 'openmaic.problem_bank',
    feature: 'problems',
    title: 'Update problem',
    description: 'Patch problem metadata, public content, grading, or notebook assignment.',
    status: 'route-backed',
    inputContract: 'Problem id, owning target id, and patch payload.',
    outputContract: 'Updated problem record.',
    entrypoints: [
      { kind: 'route', method: 'PATCH', ref: '/api/notebooks/[id]/problems/[problemId]' },
      { kind: 'route', method: 'PATCH', ref: '/api/courses/[id]/problems/[problemId]' },
    ],
    sideEffects: ['database-write'],
    requiresAuth: true,
    requiresDatabase: true,
  },
  {
    id: 'delete_problem',
    namespace: 'openmaic.problem_bank',
    feature: 'problems',
    title: 'Delete problem',
    description: 'Delete a problem from a course or notebook problem bank.',
    status: 'route-backed',
    inputContract: 'Problem id and owning target id.',
    outputContract: 'Deletion result.',
    entrypoints: [
      { kind: 'route', method: 'DELETE', ref: '/api/notebooks/[id]/problems/[problemId]' },
      { kind: 'route', method: 'DELETE', ref: '/api/courses/[id]/problems/[problemId]' },
    ],
    sideEffects: ['database-write'],
    requiresAuth: true,
    requiresDatabase: true,
  },
] satisfies readonly AgentToolDefinition[];

export const IMPORT_PROBLEM_BANK_SKILL = {
  id: 'import_problem_bank',
  title: 'Import problem bank',
  primaryUserFunction: 'Import problems',
  description:
    'Convert one source file or text block into reviewed course/notebook problem-bank records with ownership and batch traceability.',
  skillDocumentPath: 'features/agent/skills/import-problems/SKILL.md',
  skillDocumentUri: 'openmaic://skills/import_problem_bank',
  supportingSkillDocumentIds: [],
  mcpNamespaces: ['openmaic.content', 'openmaic.problem_bank'],
  toolIds: [
    'read_course_context',
    'read_notebook_context',
    'preview_problem_import',
    'commit_problem_import',
    'create_problem_from_draft',
    'update_problem',
    'delete_problem',
  ],
  stages: [
    {
      id: 'target',
      title: 'Resolve target',
      description: 'Resolve course or notebook ownership before parsing starts.',
      toolIds: ['read_course_context', 'read_notebook_context'],
      required: true,
    },
    {
      id: 'preview',
      title: 'Preview import',
      description: 'Extract and normalize drafts from a single source with quality warnings.',
      toolIds: ['preview_problem_import'],
      required: true,
    },
    {
      id: 'review',
      title: 'Review drafts',
      description: 'Let user or agent edit, skip, or retag drafts before committing.',
      toolIds: ['update_problem'],
      required: false,
    },
    {
      id: 'commit',
      title: 'Commit import',
      description: 'Persist approved drafts and mark the import batch committed.',
      toolIds: ['commit_problem_import', 'create_problem_from_draft'],
      required: true,
    },
  ],
  qualityGates: [
    'Target ownership is explicit for course-owned unassigned problems and notebook-owned problems.',
    'Preview creates traceable ProblemImportBatch state before commit.',
    'Drafts use NotebookProblemImportDraft as the normalization bridge.',
    'Figure-only or drawing-style problems can be skipped before commit when requested.',
  ],
  outputs: ['ProblemImportBatch', 'NotebookProblem records', 'Import warnings and usage metadata'],
} satisfies AgentSkillDefinition;
