import type {
  CandidateProblemPayload,
  Preset,
  PrivateMemoryPayload,
  ReviewHistoryPayload,
  ReviewMode,
  ReviewScenario,
  ReviewScenarioId,
  ReviewStepId,
} from './types';

export const REVIEW_STEPS: Record<
  ReviewStepId,
  { order: number; title: string; subtitle: string; artifact: string }
> = {
  profile: {
    order: 1,
    title: '这本 notebook 的学情',
    subtitle: '私人记忆、上一轮复习结果和本次目标',
    artifact: 'notebook memory / review history',
  },
  'problem-bank': {
    order: 2,
    title: '本轮应该选哪些题',
    subtitle: '用错题、open memory 和未尝试专题筛候选题',
    artifact: 'candidate problems / selectedProblemIds',
  },
  readiness: {
    order: 3,
    title: '题库够不够开图',
    subtitle: '识别缺题和题量偏薄的专题',
    artifact: 'readiness / missing / thin topics',
  },
  'review-plan': {
    order: 4,
    title: '下一轮复习路线',
    subtitle: '关卡要引用候选题，并修复私人记忆里的 open 点',
    artifact: 'ReviewRoute / problemIds / boss',
  },
};

export const REVIEW_SCENARIOS: Record<ReviewScenarioId, ReviewScenario> = {
  'known-memory': {
    id: 'known-memory',
    title: '有记忆用户',
    description: '用户有 notebook 私人记忆和上一轮复习记录，检查路线是否真正使用个性化信号。',
    memoryMode: 'full',
    bankMode: 'full',
    expectedSignal: '应优先命中 open memory、历史失败概念和相关错题。',
  },
  'cold-start': {
    id: 'cold-start',
    title: '完全没记忆',
    description: '用户没有私人记忆和历史复习记录，检查系统能否退回到题库画像和当前目标。',
    memoryMode: 'none',
    bankMode: 'full',
    expectedSignal: '不应该因为 privateMemory/history 为空而卡死。',
  },
  'bank-rich': {
    id: 'bank-rich',
    title: '题库充足',
    description: '题库有 20 道结构化候选题，覆盖多题型、多难度和多状态。',
    memoryMode: 'full',
    bankMode: 'full',
    expectedSignal: '应从 20 道里筛出本轮重点题，而不是全量照搬。',
  },
  'bank-empty': {
    id: 'bank-empty',
    title: '完全没题库',
    description: '题库候选题为空，检查 pipeline 是否先 AI 补题，再继续生成路线。',
    memoryMode: 'full',
    bankMode: 'empty',
    expectedSignal: 'problem-bank 应显示缺口，AI 补满后 readiness/review-plan 解锁。',
  },
  'bank-thin': {
    id: 'bank-thin',
    title: '题库不足',
    description: '只有少量候选题，检查薄弱/缺题信号和 AI 补题数量是否清楚。',
    memoryMode: 'full',
    bankMode: 'thin',
    expectedSignal: '应保留已有候选题，并按缺口补齐所需题量。',
  },
};

export const PRESETS: Record<ReviewMode, Preset> = {
  'exam-sprint': {
    id: 'exam-sprint',
    title: '考试冲刺',
    description: '更关注高频考点、综合 Boss 和限时检测。',
    goal: '48 小时内补齐期末前最容易丢分的专题，路线要短、分支清楚、Boss 综合度高。',
    weakPoints: '链式法则遇到复合函数时容易漏乘内层导数\n极限题看不出等价无穷小替换时机',
    masteredConcepts: '导数定义\n基本求导公式\n连续与间断点',
    weakConcepts: '链式法则\n隐函数求导',
    untriedConcepts: '洛必达法则\n参数方程求导',
    thinConcepts: '泰勒展开\n极值判定',
    missingConcepts: '综合应用题',
    customRules: 'Boss 关必须混合至少 3 个知识点；普通关题目数量控制在 2-3 题。',
    intensity: 5,
    includeSupportNodes: true,
    forceBossMix: true,
  },
  'mistake-repair': {
    id: 'mistake-repair',
    title: '错题修复',
    description: '把错题、薄弱概念和未尝试专题放到路线前半段。',
    goal: '围绕最近错题生成一条修复路线，先补小漏洞，再用精英关确认迁移能力。',
    weakPoints: '递推式复杂度分析总是漏掉边界条件\n链表指针更新时容易把 prev 和 curr 写反',
    masteredConcepts: 'Python 函数调用\n基础类定义\n列表遍历',
    weakConcepts: '递归复杂度\n链表删除',
    untriedConcepts: '继承方法解析顺序\n异常处理',
    thinConcepts: '二叉树遍历\n栈帧追踪',
    missingConcepts: '',
    customRules: '前两层优先安排错题概念；每个精英关都要写清楚变式来源。',
    intensity: 4,
    includeSupportNodes: true,
    forceBossMix: true,
  },
  'gentle-foundation': {
    id: 'gentle-foundation',
    title: '低压打底',
    description: '适合刚开始复习或信心不足时，增加营火和宝箱节奏。',
    goal: '不要一开始就高压，先用基础题确认安全区，再逐步接触未尝试专题。',
    weakPoints: '看到抽象定义会紧张，容易跳过题干条件\n证明题不知道第一句该从哪里写',
    masteredConcepts: '集合基本运算\n命题逻辑符号',
    weakConcepts: '等价关系\n偏序关系',
    untriedConcepts: '同余类\n商集',
    thinConcepts: '反例构造',
    missingConcepts: '综合证明',
    customRules: '第一层必须温和；每两层至少有一个恢复节奏的非做题节点。',
    intensity: 2,
    includeSupportNodes: true,
    forceBossMix: false,
  },
};

export const CANDIDATE_PROBLEM_FIXTURES: Record<ReviewMode, CandidateProblemPayload[]> = {
  'exam-sprint': [
    {
      id: 'calc-chain-choice-01',
      title: '复合函数链式法则单选',
      type: 'choice',
      concepts: ['链式法则', '基本求导公式'],
      difficulty: 'easy',
      status: 'passed',
      score: 4,
      tags: ['calculus', 'choice'],
      preview: '判断 $\\frac{d}{dx}\\sin(x^2)$ 的内层导数是否漏乘。',
    },
    {
      id: 'calc-chain-calc-02',
      title: '多层复合函数求导',
      type: 'calculation',
      concepts: ['链式法则'],
      difficulty: 'medium',
      status: 'failed',
      score: 3,
      tags: ['calculus', 'calculation', 'wrong_problem'],
      preview: '计算 $y=e^{\\sin(3x^2)}$ 的导数并标出每一层。',
    },
    {
      id: 'calc-limit-short-03',
      title: '等价无穷小替换时机',
      type: 'short_answer',
      concepts: ['极限', '等价无穷小'],
      difficulty: 'medium',
      status: 'partial',
      score: 5,
      tags: ['limit', 'short_answer'],
      preview: '说明什么时候可以把 $\\sin x$ 替换成 $x$。',
    },
    {
      id: 'calc-lhopital-04',
      title: '洛必达法则适用条件',
      type: 'choice',
      concepts: ['洛必达法则', '极限'],
      difficulty: 'medium',
      status: 'unattempted',
      score: null,
      tags: ['limit', 'untried'],
      preview: '判断哪些极限形式可以直接使用洛必达法则。',
    },
    {
      id: 'calc-implicit-05',
      title: '隐函数求导错因修复',
      type: 'calculation',
      concepts: ['隐函数求导', '链式法则'],
      difficulty: 'hard',
      status: 'failed',
      score: 2,
      tags: ['implicit', 'wrong_problem'],
      preview: '对 $x^2+xy+y^2=7$ 求 $dy/dx$。',
    },
    {
      id: 'calc-parametric-06',
      title: '参数方程切线斜率',
      type: 'calculation',
      concepts: ['参数方程求导'],
      difficulty: 'medium',
      status: 'unattempted',
      tags: ['parametric', 'untried'],
      preview: '由 $x=t^2+1,y=t^3-t$ 求指定点切线斜率。',
    },
    {
      id: 'calc-taylor-07',
      title: '泰勒展开近似误差',
      type: 'short_answer',
      concepts: ['泰勒展开'],
      difficulty: 'hard',
      status: 'partial',
      score: 6,
      tags: ['thin_bank'],
      preview: '用二阶泰勒展开估算并说明余项含义。',
    },
    {
      id: 'calc-extrema-08',
      title: '极值判定与二阶导数',
      type: 'proof',
      concepts: ['极值判定', '连续与间断点'],
      difficulty: 'medium',
      status: 'passed',
      score: 10,
      tags: ['review'],
      preview: '证明局部极值点的一阶导必要条件，并讨论例外。',
    },
    {
      id: 'calc-chain-fill-09',
      title: '链式法则步骤填空',
      type: 'fill_blank',
      concepts: ['链式法则', '基本求导公式'],
      difficulty: 'easy',
      status: 'partial',
      score: 4,
      tags: ['calculus', 'fill_blank'],
      preview: '补全 $\\ln(1+x^2)$ 求导时的外层和内层导数。',
    },
    {
      id: 'calc-limit-calc-10',
      title: '夹逼与等价无穷小混合',
      type: 'calculation',
      concepts: ['极限', '等价无穷小'],
      difficulty: 'hard',
      status: 'failed',
      score: 2,
      tags: ['limit', 'wrong_problem'],
      preview: '计算含 $\\sin x-x$ 的高阶极限，并说明不能直接替换的位置。',
    },
    {
      id: 'calc-optimization-11',
      title: '单变量优化应用题',
      type: 'calculation',
      concepts: ['极值判定', '应用建模'],
      difficulty: 'medium',
      status: 'unattempted',
      tags: ['optimization', 'untried'],
      preview: '建立面积最大问题的一元函数并求临界点。',
    },
    {
      id: 'calc-continuity-12',
      title: '分段函数连续性判断',
      type: 'choice',
      concepts: ['连续与间断点', '极限'],
      difficulty: 'easy',
      status: 'passed',
      score: 5,
      tags: ['continuity'],
      preview: '判断分段函数在拼接点处是否连续。',
    },
    {
      id: 'calc-code-derivative-13',
      title: '数值导数函数测试',
      type: 'code',
      concepts: ['导数定义', '基本求导公式'],
      difficulty: 'medium',
      status: 'unattempted',
      tags: ['code', 'test_cases'],
      preview: '实现 numerical_derivative(f, x, h)，用 public/hidden tests 检查精度。',
    },
    {
      id: 'calc-mvt-proof-14',
      title: '中值定理条件辨析',
      type: 'proof',
      concepts: ['连续与间断点', '导数定义'],
      difficulty: 'hard',
      status: 'partial',
      score: 6,
      tags: ['proof', 'thin_bank'],
      preview: '说明拉格朗日中值定理为什么需要闭区间连续、开区间可导。',
    },
    {
      id: 'calc-related-rates-15',
      title: '相关变化率建模',
      type: 'short_answer',
      concepts: ['隐函数求导', '应用建模'],
      difficulty: 'medium',
      status: 'failed',
      score: 3,
      tags: ['implicit', 'wrong_problem'],
      preview: '解释半径变化率和面积变化率之间为什么要先建立函数关系。',
    },
    {
      id: 'calc-parametric-choice-16',
      title: '参数方程水平切线判断',
      type: 'choice',
      concepts: ['参数方程求导', '极值判定'],
      difficulty: 'medium',
      status: 'passed',
      score: 5,
      tags: ['parametric'],
      preview: '判断何时 $dy/dx=0$ 且 $dx/dt\\neq0$。',
    },
    {
      id: 'calc-taylor-fill-17',
      title: '泰勒展开系数填空',
      type: 'fill_blank',
      concepts: ['泰勒展开', '基本求导公式'],
      difficulty: 'medium',
      status: 'unattempted',
      tags: ['taylor', 'fill_blank'],
      preview: '补全 $e^x$ 在 0 点的三阶展开。',
    },
    {
      id: 'calc-lhopital-calc-18',
      title: '洛必达连续使用边界',
      type: 'calculation',
      concepts: ['洛必达法则', '极限'],
      difficulty: 'hard',
      status: 'partial',
      score: 5,
      tags: ['lhopital', 'thin_bank'],
      preview: '计算一个需要两次洛必达但必须先确认未定式的极限。',
    },
    {
      id: 'calc-graph-short-19',
      title: '导函数图像信息读取',
      type: 'short_answer',
      concepts: ['极值判定', '连续与间断点'],
      difficulty: 'medium',
      status: 'passed',
      score: 8,
      tags: ['graph'],
      preview: '根据 $f\\prime(x)$ 图像判断 $f(x)$ 的增减和极值。',
    },
    {
      id: 'calc-final-boss-20',
      title: '期末综合小 Boss',
      type: 'calculation',
      concepts: ['链式法则', '隐函数求导', '洛必达法则', '泰勒展开'],
      difficulty: 'hard',
      status: 'unattempted',
      tags: ['boss_mix'],
      preview: '混合复合求导、隐函数和极限近似，要求写出分步策略。',
    },
  ],
  'mistake-repair': [
    {
      id: 'cs-recursion-choice-01',
      title: '递归复杂度边界判断',
      type: 'choice',
      concepts: ['递归复杂度', '栈帧追踪'],
      difficulty: 'medium',
      status: 'failed',
      score: 2,
      tags: ['recursion', 'wrong_problem'],
      preview: '分析 $T(n)=2T(n/2)+n$ 与 base case 的关系。',
    },
    {
      id: 'cs-recursion-code-02',
      title: '递归展开计数函数',
      type: 'code',
      concepts: ['递归复杂度', 'Python 函数调用'],
      difficulty: 'medium',
      status: 'partial',
      score: 12,
      tags: ['code', 'recursion'],
      preview: '实现 count_calls(n)，用 public/hidden tests 检查 base case。',
    },
    {
      id: 'cs-linked-list-code-03',
      title: '删除链表中指定节点',
      type: 'code',
      concepts: ['链表删除', '列表遍历'],
      difficulty: 'hard',
      status: 'failed',
      score: 8,
      tags: ['code', 'linked_list', 'wrong_problem'],
      preview: '实现 remove_value(head, target)，避免 prev/curr 写反。',
    },
    {
      id: 'cs-oop-code-04',
      title: '方法解析顺序追踪',
      type: 'code',
      concepts: ['继承方法解析顺序', '基础类定义'],
      difficulty: 'medium',
      status: 'unattempted',
      tags: ['oop', 'code', 'untried'],
      preview: '给出 class A/B/C，判断 super() 调用顺序并补全方法。',
    },
    {
      id: 'cs-exception-fill-05',
      title: '异常处理流程填空',
      type: 'fill_blank',
      concepts: ['异常处理'],
      difficulty: 'easy',
      status: 'unattempted',
      tags: ['exception', 'fill_blank'],
      preview: '填写 try/except/finally 的执行顺序。',
    },
    {
      id: 'cs-tree-traversal-06',
      title: '二叉树遍历输出',
      type: 'short_answer',
      concepts: ['二叉树遍历', '栈帧追踪'],
      difficulty: 'medium',
      status: 'partial',
      score: 6,
      tags: ['thin_bank'],
      preview: '根据树结构写出前序、中序和后序遍历。',
    },
    {
      id: 'cs-stack-frame-07',
      title: '栈帧追踪简答',
      type: 'short_answer',
      concepts: ['栈帧追踪', '递归复杂度'],
      difficulty: 'hard',
      status: 'partial',
      score: 7,
      tags: ['stack_frame', 'thin_bank'],
      preview: '画出 recursive_sum(4) 的调用栈，并指出返回顺序。',
    },
    {
      id: 'cs-boss-debug-08',
      title: '递归链表综合 Debug',
      type: 'code',
      concepts: ['递归复杂度', '链表删除', '异常处理'],
      difficulty: 'hard',
      status: 'unattempted',
      tags: ['boss_mix', 'code'],
      preview: '修复一个递归删除链表节点的函数，并处理空链表异常。',
    },
  ],
  'gentle-foundation': [
    {
      id: 'disc-set-choice-01',
      title: '集合运算安全区',
      type: 'choice',
      concepts: ['集合基本运算'],
      difficulty: 'easy',
      status: 'passed',
      score: 5,
      tags: ['sets', 'foundation'],
      preview: '判断 $A\\cap(B\\cup C)$ 与分配律相关选项。',
    },
    {
      id: 'disc-logic-fill-02',
      title: '命题逻辑符号填空',
      type: 'fill_blank',
      concepts: ['命题逻辑符号'],
      difficulty: 'easy',
      status: 'passed',
      score: 4,
      tags: ['logic'],
      preview: '补全 $p\\Rightarrow q$ 的逆否命题。',
    },
    {
      id: 'disc-equivalence-proof-03',
      title: '等价关系三条件证明',
      type: 'proof',
      concepts: ['等价关系'],
      difficulty: 'medium',
      status: 'failed',
      score: 3,
      tags: ['proof', 'wrong_problem'],
      preview: '证明关系满足自反、对称、传递。',
    },
    {
      id: 'disc-poset-choice-04',
      title: '偏序关系反例选择',
      type: 'choice',
      concepts: ['偏序关系', '反例构造'],
      difficulty: 'medium',
      status: 'partial',
      score: 4,
      tags: ['poset', 'thin_bank'],
      preview: '判断一个关系为什么不是偏序。',
    },
    {
      id: 'disc-congruence-calc-05',
      title: '同余类代表元计算',
      type: 'calculation',
      concepts: ['同余类'],
      difficulty: 'medium',
      status: 'unattempted',
      tags: ['congruence', 'untried'],
      preview: '计算 $[17]_5$ 并列出同余类里的三个代表元。',
    },
    {
      id: 'disc-quotient-short-06',
      title: '商集直觉解释',
      type: 'short_answer',
      concepts: ['商集', '同余类'],
      difficulty: 'hard',
      status: 'unattempted',
      tags: ['quotient', 'untried'],
      preview: '用自然语言解释为什么商集把元素按等价关系分组。',
    },
    {
      id: 'disc-counterexample-07',
      title: '反例构造小题',
      type: 'short_answer',
      concepts: ['反例构造', '偏序关系'],
      difficulty: 'medium',
      status: 'partial',
      score: 5,
      tags: ['counterexample', 'thin_bank'],
      preview: '构造一个满足自反但不满足反对称的关系。',
    },
    {
      id: 'disc-boss-proof-08',
      title: '等价关系与商集综合证明',
      type: 'proof',
      concepts: ['等价关系', '商集'],
      difficulty: 'hard',
      status: 'unattempted',
      tags: ['boss_mix', 'proof'],
      preview: '从等价关系出发说明商集划分，并给出一个具体例子。',
    },
  ],
};

export const PRIVATE_MEMORY_FIXTURES: Record<ReviewMode, PrivateMemoryPayload[]> = {
  'exam-sprint': [
    {
      id: 'mem-calc-chain',
      concept: '链式法则',
      note: '最近两次求导都漏乘内层导数，尤其遇到三层复合函数会跳步。',
      status: 'open',
      severity: 'high',
      source: 'notebook_private_memory',
      relatedProblemIds: ['calc-chain-calc-02', 'calc-implicit-05'],
    },
    {
      id: 'mem-calc-limit',
      concept: '等价无穷小',
      note: '知道结论，但在加减结构里会误用替换。',
      status: 'open',
      severity: 'medium',
      source: 'notebook_private_memory',
      relatedProblemIds: ['calc-limit-short-03'],
    },
    {
      id: 'mem-calc-derivative-definition',
      concept: '导数定义',
      note: '上一轮已经完成基础定义复习，可以低频巩固。',
      status: 'reviewed',
      severity: 'low',
      source: 'notebook_private_memory',
      relatedProblemIds: ['calc-chain-choice-01'],
    },
  ],
  'mistake-repair': [
    {
      id: 'mem-cs-recursion',
      concept: '递归复杂度',
      note: '能写递归，但解释时间复杂度时总是忘记 base case 和递归树层数。',
      status: 'open',
      severity: 'high',
      source: 'notebook_private_memory',
      relatedProblemIds: ['cs-recursion-choice-01', 'cs-recursion-code-02'],
    },
    {
      id: 'mem-cs-linked-list',
      concept: '链表删除',
      note: 'prev/curr 指针更新顺序不稳，需要安排代码题返修。',
      status: 'open',
      severity: 'high',
      source: 'notebook_private_memory',
      relatedProblemIds: ['cs-linked-list-code-03'],
    },
    {
      id: 'mem-cs-functions',
      concept: 'Python 函数调用',
      note: '函数调用基础已复习过，可放进 Boss 综合题巩固。',
      status: 'reviewed',
      severity: 'low',
      source: 'notebook_private_memory',
      relatedProblemIds: ['cs-recursion-code-02'],
    },
  ],
  'gentle-foundation': [
    {
      id: 'mem-disc-proof-start',
      concept: '等价关系',
      note: '证明题第一句不知道从哪里写，遇到“证明是关系”会紧张。',
      status: 'open',
      severity: 'high',
      source: 'notebook_private_memory',
      relatedProblemIds: ['disc-equivalence-proof-03'],
    },
    {
      id: 'mem-disc-counterexample',
      concept: '反例构造',
      note: '能看懂反例，但自己构造时会过早放弃。',
      status: 'open',
      severity: 'medium',
      source: 'notebook_private_memory',
      relatedProblemIds: ['disc-poset-choice-04'],
    },
    {
      id: 'mem-disc-sets',
      concept: '集合基本运算',
      note: '基础集合运算已经稳定，可以作为第一层安全区。',
      status: 'reviewed',
      severity: 'low',
      source: 'notebook_private_memory',
      relatedProblemIds: ['disc-set-choice-01'],
    },
  ],
};

export const REVIEW_HISTORY_FIXTURES: Record<ReviewMode, ReviewHistoryPayload[]> = {
  'exam-sprint': [
    {
      id: 'hist-calc-1',
      title: '上一轮：基础求导热身',
      status: 'completed',
      coveredConcepts: ['导数定义', '基本求导公式'],
      failedConcepts: [],
      problemIds: ['calc-chain-choice-01'],
    },
    {
      id: 'hist-calc-2',
      title: '上一轮 Boss：复合函数与极限混合',
      status: 'failed',
      coveredConcepts: ['链式法则', '极限'],
      failedConcepts: ['链式法则', '等价无穷小'],
      problemIds: ['calc-chain-calc-02', 'calc-limit-short-03'],
    },
  ],
  'mistake-repair': [
    {
      id: 'hist-cs-1',
      title: '上一轮：列表遍历和函数调用',
      status: 'completed',
      coveredConcepts: ['列表遍历', 'Python 函数调用'],
      failedConcepts: [],
      problemIds: ['cs-recursion-code-02'],
    },
    {
      id: 'hist-cs-2',
      title: '上一轮：指针删除挑战',
      status: 'partial',
      coveredConcepts: ['链表删除'],
      failedConcepts: ['链表删除'],
      problemIds: ['cs-linked-list-code-03'],
    },
  ],
  'gentle-foundation': [
    {
      id: 'hist-disc-1',
      title: '上一轮：集合与逻辑安全区',
      status: 'completed',
      coveredConcepts: ['集合基本运算', '命题逻辑符号'],
      failedConcepts: [],
      problemIds: ['disc-set-choice-01', 'disc-logic-fill-02'],
    },
    {
      id: 'hist-disc-2',
      title: '上一轮：证明开头练习',
      status: 'failed',
      coveredConcepts: ['等价关系'],
      failedConcepts: ['等价关系'],
      problemIds: ['disc-equivalence-proof-03'],
    },
  ],
};
