export const MEMORY_REVIEW_PLAN_TOOL_IDS = [
  'read_user_profile',
  'read_calendar',
  'search_learning_memory',
  'search_problem_attempts',
  'search_problem_bank',
  'search_notebooks',
] as const;

export type MemoryReviewPlanToolId = (typeof MEMORY_REVIEW_PLAN_TOOL_IDS)[number];

export type MemoryReviewPlanRequest = {
  action: 'generate_review_plan';
  user: {
    id: string;
    name: string;
    courseCode: 'CSC148';
    learnerProfile: unknown;
    studyHabit: unknown;
  };
  query: string;
  today: string;
  constraints: {
    totalMinutes: number;
    maxSessions: number;
    maxQuestionsPerSession: number;
  };
  sources: {
    calendar: Array<{
      id: string;
      title: string;
      startsAt: string;
      endsAt: string | null;
      timezone: string;
      status: string;
    }>;
    memories: Array<{
      id: string;
      title: string;
      text: string;
      kind: string;
      scope: string;
      status: string;
      updatedAt: number;
    }>;
    attempts: Array<{
      id: string;
      problemId: string;
      problemTitle: string;
      concept: string;
      status: string;
      score: number;
      maxScore: number | null;
      feedback: string;
      createdAt: number;
    }>;
    notebooks: Array<{
      id: string;
      title: string;
      content: string;
      updatedAt: number;
    }>;
  };
};

export type MemoryReviewPlanEvidence = {
  id: string;
  sourceType: 'profile' | 'schedule' | 'memory' | 'attempt' | 'problem' | 'notebook';
  title: string;
  excerpt: string;
  sourceId: string;
  score: number | null;
  /** Source timestamp used to honor requests that explicitly limit evidence to the latest records. */
  observedAt?: number;
};

export type MemoryReviewPlanToolCall = {
  toolId: MemoryReviewPlanToolId;
  reason: string;
  query: string | null;
  limit: number;
};

export type MemoryReviewPlanToolTrace = MemoryReviewPlanToolCall & {
  status: 'completed' | 'failed';
  startedAt: string;
  durationMs: number;
  outputEvidenceIds: string[];
  error: string | null;
};

export type MemoryReviewPlanQuestion = {
  problemId: string;
  title: string;
  href: string;
  type: string;
  difficulty: string;
  tags: string[];
  reason: string;
  evidenceIds: string[];
};

export type MemoryReviewPlanResponse = {
  action: 'generate_review_plan';
  model: string;
  readPlan: {
    reasoning: string[];
    calls: MemoryReviewPlanToolCall[];
  };
  trace: MemoryReviewPlanToolTrace[];
  evidence: MemoryReviewPlanEvidence[];
  problemBank: {
    courseCode: 'CSC148';
    /** Required on newly generated results; optional so older latest-only records remain readable. */
    courseId?: string;
    source: string;
    totalCount: number;
    selected: Array<{
      id: string;
      sourceId?: string;
      title: string;
      type: string;
      difficulty: string;
      tags: string[];
      question: string;
      hybridScore: number;
      /** Added by the server from courseId + id, never generated by the model. */
      href?: string;
    }>;
  };
  plan: {
    /** Required on newly generated results; optional so older latest-only records remain readable. */
    userMessage?: string;
    title: string;
    summary: string;
    deadlineSummary: string;
    priorities: Array<{
      concept: string;
      reason: string;
      evidenceIds: string[];
    }>;
    sessions: Array<{
      id: string;
      dayLabel: string;
      date: string;
      startTime: string;
      minutes: number;
      focus: string;
      method: string;
      reason: string;
      evidenceIds: string[];
      problemIds: string[];
      /** New responses always include this; optional keeps existing local records readable. */
      questions?: MemoryReviewPlanQuestion[];
      questionCount: number;
      completionSignal: string;
    }>;
    warnings: string[];
  };
  machineChecks: Array<{
    id: string;
    label: string;
    passed: boolean;
    detail: string;
  }>;
  passedMachineCheck: boolean;
  usage: {
    inputTokens: number;
    outputTokens: number;
    cachedInputTokens: number;
    totalTokens: number;
  };
  persistence: 'none';
};
