import type { SceneOutline } from '@/lib/types/generation';

import type { QualityPreset } from './page-types';

export const DEFAULT_OUTLINE_DESCRIPTION = [
  '本页用 Tweet 的 list/dict 表示作为失败案例，说明旧表示能存数据但守不住对象状态规则。',
  '学生应从 Tweet() 入口先判断对象需要哪些字段、哪些错误状态会被旧表示接受，再看到定义类的必要性。',
].join('\n');

export const DEFAULT_TITLE = '从 Tweet() 看：旧表示为什么守不住规则';
export const DEFAULT_KEY_POINTS = [
  "合法 list: ['David', '2017-09-19', 'Hello, I am so cool', 0]。",
  "错误 list: [55, 'Diane', 'Older and even cooler', '2017-09-19'] 会把 likes、userid、content、date 的位置和类型弄乱。",
  "缺少日期的 dict: {'userid': 'Jacqueline', 'content': 'Has the most dignified cat', 'likes': 12} 仍然可能被客户端传来。",
  'Tweet 需要作者、日期、内容、点赞数；客户端代码可以直接操作 list 和 dict。',
  '结论落到为什么要定义 Tweet()：字段名字、初始化和操作边界集中在类里。',
];

export const CODE_SPLIT_SNIPPET = [
  'class Tweet:',
  '    def __init__(self, who: str, when: date, what: str) -> None:',
  '        self.userid = who',
  '        self.created_at = when',
  '        self.content = what',
  '        self.likes = 0',
  '',
  "t1 = Tweet('Giovanna', date(2017, 9, 18), 'Hello')",
].join('\n');

export const TWEET_SHARED_EXAMPLE: NonNullable<SceneOutline['sharedExamples']>[number] = {
  id: 'tweet_object_example',
  label: 'Tweet',
  aliases: ['Tweet', 'Tweet()', 'tweet', 't1'],
  description:
    '贯穿本组页面的 OOP 例子：一条 Tweet 需要把作者、日期、内容、点赞数作为同一对象的状态来维护。',
  canonicalData: [
    "合法 list: ['David', '2017-09-19', 'Hello, I am so cool', 0]",
    'Tweet 状态字段: userid, created_at, content, likes',
  ],
  malformedData: [
    "错误 list: [55, 'Diane', 'Older and even cooler', '2017-09-19']",
    "缺少日期的 dict: {'userid': 'Jacqueline', 'content': 'Has the most dignified cat', 'likes': 12}",
  ],
  rules: [
    'list 守不住字段名字和顺序语义。',
    'dict 守不住初始化完整性和允许操作边界。',
    'Tweet 类应该集中字段、初始化和点赞等操作。',
  ],
  lessonRole: '用同一个 Tweet 例子连接旧表示失败、类的边界和 self/初始化。',
};

export const QUALITY_PRESETS: QualityPreset[] = [
  {
    id: 'hero_courtyard_overlay',
    label: '图片封面',
    description: '测试整页图片 + 左侧标题遮罩的课程导入/章节封面。',
    title: '第一次打造小院就成功',
    outlineDescription:
      '本页是课程开场封面，用一个温暖庭院场景承接主题，让学生先进入“从规划到落地”的学习情境。',
    keyPoints: [
      '从规划到养护，系统梳理小院打造的关键路径。',
      '面向第一次做庭院的人，强调可执行和少踩坑。',
    ],
    layoutTemplate: 'image_title_overlay',
    deckStyle: 'magazine',
    contentProfile: 'general',
    archetype: 'intro',
    disciplineStyle: 'general',
    teachingFlow: 'standalone',
    visualRole: 'source_image',
    overflowPolicy: 'compress_first',
    teachingRole: 'concept_model',
    teachingObjective: '学生能用一个清晰入口理解本课程围绕小院打造展开。',
    openingMove: '先用庭院场景建立本节课的主题和对象。',
    concreteAnchor: '第一次打造小院：从规划到养护，少走弯路。',
    studentThinkingMove: '让学生先判断自己要解决的是空间规划、植物选择还是维护路径。',
    transferRule: '开场封面只建立主题、对象和学习入口。',
    requiredComponentKinds: ['example'],
    expectedAnchors: ['小院', '规划'],
  },
  {
    id: 'hero_cinematic_mv',
    label: '电影封面',
    description: '测试暗色电影/MV/艺术主题封面：居中标题、暗色遮罩、装饰角标。',
    title: '深度解析《太阳之子》MV',
    outlineDescription:
      '本页是影像解析章节封面，用电影感主视觉建立观看角度：画面、人物、主题如何彼此呼应。',
    keyPoints: [
      '从画面构图、叙事线索和主题隐喻三个角度进入。',
      '把学生注意力从“看到了什么”带到“为什么这样拍”。',
    ],
    layoutTemplate: 'cinematic_title_frame',
    deckStyle: 'dark_art',
    contentProfile: 'general',
    archetype: 'intro',
    disciplineStyle: 'humanities',
    teachingFlow: 'close_reading',
    visualRole: 'source_image',
    overflowPolicy: 'compress_first',
    teachingRole: 'evidence_frame',
    teachingObjective: '学生能带着明确解析角度进入影像文本。',
    openingMove: '先建立这段 MV 的观看框架。',
    concreteAnchor: '《太阳之子》MV：画面、人物、主题三条线索。',
    studentThinkingMove: '让学生先找一个画面细节，再说它可能服务什么主题。',
    transferRule: '影像解析先定观察角度，再进入证据。',
    requiredComponentKinds: ['quote'],
    expectedAnchors: ['太阳之子', 'MV'],
  },
  {
    id: 'hero_tech_subscription',
    label: '科技封面',
    description: '测试暗色科技/SaaS 封面：抽象网络背景、居中标题、短副标题。',
    title: 'Claude AI Subscription Plans',
    outlineDescription:
      'This cover opens a pricing and feature comparison deck with a clean tech/SaaS visual tone.',
    keyPoints: [
      'Complete guide to pricing, features and best value.',
      'Make the title readable over a dark abstract network background.',
    ],
    language: 'en-US',
    layoutTemplate: 'tech_hero_title',
    deckStyle: 'tech_saas',
    contentProfile: 'general',
    archetype: 'intro',
    disciplineStyle: 'general',
    teachingFlow: 'standalone',
    visualRole: 'source_image',
    overflowPolicy: 'compress_first',
    teachingRole: 'comparison',
    teachingObjective:
      'Learners enter a pricing comparison deck with the product and promise clear.',
    openingMove: 'Start from the product and what decision this deck helps make.',
    concreteAnchor: 'Claude AI subscription plans: pricing, features, and best value.',
    studentThinkingMove: 'Ask which plan dimension matters before comparing numbers.',
    transferRule:
      'A tech cover should make product, category, and decision promise immediately visible.',
    requiredComponentKinds: ['chart'],
    expectedAnchors: ['Claude AI', 'pricing'],
  },
  {
    id: 'common_project_pipeline',
    label: '通用流程表',
    description: '测试大众商务/课堂 PPT：上方阶段流程，下方输入、动作、输出对照表。',
    title: '四阶段完成一次课程项目',
    outlineDescription: [
      '本页面向普通课程项目管理，把一次项目从选题到复盘拆成四个阶段。',
      '页面应先给出横向流程，再用表格说明每个阶段的输入、主要动作和产出。',
    ].join('\n'),
    keyPoints: [
      '阶段 1：定题，明确要解决的问题和提交标准。',
      '阶段 2：收集材料，把案例、数据和参考资料放到同一工作区。',
      '阶段 3：制作初稿，先完成可讲清楚的版本，再修视觉和细节。',
      '阶段 4：演示复盘，用反馈决定下一轮修改。',
    ],
    layoutTemplate: 'pipeline_table',
    deckStyle: 'classic_business',
    contentProfile: 'general',
    archetype: 'concept',
    disciplineStyle: 'general',
    teachingFlow: 'concept_explain',
    visualRole: 'diagram',
    teachingRole: 'concept_model',
    teachingObjective: '学生能把一个项目拆成阶段、输入、动作和产出。',
    openingMove: '先把完整项目看成一条可执行流程，而不是一堆零散任务。',
    concreteAnchor: '一次课程项目：定题、收集材料、制作初稿、演示复盘。',
    studentThinkingMove: '让学生判断自己当前卡在哪个阶段，以及缺的是输入、动作还是产出。',
    transferRule: '讲流程时先画阶段，再用表格对齐每阶段的输入、动作和输出。',
    requiredComponentKinds: ['table'],
    expectedAnchors: ['定题', '初稿', '复盘'],
  },
  {
    id: 'common_comparison_matrix',
    label: '通用对照表',
    description: '测试以表格/矩阵为主体的普通 PPT：按维度比较多个方案。',
    title: '三种课程交付方案怎么选',
    outlineDescription: [
      '本页面向课程团队比较三种交付方案：手工整理、统一模板和自动生成。',
      '页面应以对照表为主体，按速度、一致性、维护成本和适用场景组织判断。',
    ].join('\n'),
    keyPoints: [
      '方案 A：手工整理，启动快，但一致性和维护成本最不稳定。',
      '方案 B：统一模板，速度中等，一致性最高，适合多人协作。',
      '方案 C：自动生成，批量效率最高，但需要明确输入规范和质检。',
      '选择规则：一次性任务看速度，长期协作看一致性，批量生产看自动化边界。',
    ],
    layoutTemplate: 'comparison_matrix',
    deckStyle: 'academic',
    contentProfile: 'general',
    archetype: 'concept',
    disciplineStyle: 'general',
    teachingFlow: 'comparison_review',
    visualRole: 'none',
    teachingRole: 'comparison',
    teachingObjective: '学生能用多个维度比较方案，而不是只凭单一偏好选择。',
    openingMove: '先把“哪个好”拆成速度、一致性、维护成本和适用场景四个维度。',
    concreteAnchor:
      '三种方案：手工整理、统一模板、自动生成；四个维度：速度、一致性、维护成本、适用场景。',
    studentThinkingMove: '让学生先选一个最重要的维度，再用表格解释选择理由。',
    transferRule: '做方案比较时，先列方案，再列维度，最后把选择规则写成一句话。',
    requiredComponentKinds: ['table'],
    expectedAnchors: ['手工整理', '统一模板', '自动生成'],
  },
  {
    id: 'common_process_flowchart',
    label: '通用流程图',
    description: '测试以流程图/步骤图为主体的普通 PPT：只画路径，不混成表格。',
    title: '从需求到发布的五步流程',
    outlineDescription: [
      '本页面向产品/课程项目说明一次需求从收集到发布的标准路径。',
      '页面应以流程图为主体，让学生看到每一步的动作和下一步进入条件。',
    ].join('\n'),
    keyPoints: [
      '收集需求：记录用户原话和出现频率。',
      '归类问题：把相似反馈合并成同一个问题。',
      '确定方案：写清楚要改什么、不改什么。',
      '制作验证：先做可测试版本，用真实场景检查。',
      '发布复盘：上线后看数据和反馈，决定下一轮。',
    ],
    layoutTemplate: 'process_steps',
    deckStyle: 'tech_saas',
    contentProfile: 'general',
    archetype: 'concept',
    disciplineStyle: 'general',
    teachingFlow: 'timeline_story',
    visualRole: 'diagram',
    teachingRole: 'concept_model',
    teachingObjective: '学生能把一个交付流程拆成有进入条件的连续步骤。',
    openingMove: '先把需求交付看成一条可检查的路径，而不是一次性完成的任务。',
    concreteAnchor: '需求路径：收集需求 → 归类问题 → 确定方案 → 制作验证 → 发布复盘。',
    studentThinkingMove: '让学生判断自己当前需求卡在哪一步，以及下一步进入条件是什么。',
    transferRule: '画流程图时，每一步都要写动作，并说明它如何进入下一步。',
    requiredComponentKinds: ['chart'],
    expectedAnchors: ['收集需求', '确定方案', '发布复盘'],
  },
  {
    id: 'common_feature_text_image',
    label: '通用左右图文',
    description: '测试最常见的左文本、右图片版式：一个核心观点配一个视觉证据。',
    title: '把用户反馈变成可执行需求',
    outlineDescription: [
      '本页讲产品迭代中如何从用户反馈提炼需求。',
      '左侧应保留短文本讲清判断，右侧用图示呈现反馈、问题、需求之间的关系。',
      '样本反馈是：“导出课程报告太慢，开会前经常来不及。”',
    ].join('\n'),
    keyPoints: [
      '样本反馈：导出课程报告太慢，开会前经常来不及。',
      '先抽问题：报告导出耗时过长，影响会前准备。',
      '再写需求：支持后台导出并在完成后提醒用户。',
      '补验收标准：10 页报告 2 分钟内完成；超时也要给完成通知。',
    ],
    layoutTemplate: 'text_image_split',
    deckStyle: 'tech_saas',
    contentProfile: 'general',
    archetype: 'concept',
    disciplineStyle: 'general',
    teachingFlow: 'concept_explain',
    visualRole: 'generated_image',
    teachingRole: 'concept_model',
    teachingObjective: '学生能从反馈、问题、需求三个层次区分产品输入。',
    openingMove: '先把用户说的话和真正要解决的问题分开。',
    concreteAnchor:
      '样本反馈：`导出课程报告太慢，开会前经常来不及`；问题：`报告导出耗时过长`；需求：`后台导出并提醒`；验收：`10 页报告 2 分钟内完成，超时也通知`。',
    studentThinkingMove: '让学生把一句用户抱怨改写成一个可执行需求。',
    transferRule: '遇到反馈时，先抽问题，再写需求，最后补验收标准。',
    requiredComponentKinds: ['example'],
    expectedAnchors: ['导出课程报告太慢', '后台导出', '验收'],
    mediaGenerations: [
      {
        type: 'image',
        elementId: 'gen_img_1',
        aspectRatio: '16:9',
        style: 'clean product workflow diagram',
        prompt:
          'A clean product workflow diagram showing a slow report export user complaint becoming a grouped problem, then a background export requirement with acceptance criteria. Minimal SaaS classroom style.',
      },
    ],
  },
  {
    id: 'common_four_principles',
    label: '通用四栏',
    description: '测试四个并列原则/卖点/检查项的普通 PPT 版式。',
    title: '一次好汇报的四个基本原则',
    outlineDescription: [
      '本页总结普通课堂和工作汇报都适用的四个原则。',
      '页面应是四栏并列，每栏只放一个原则和一句可执行说明。',
    ].join('\n'),
    keyPoints: [
      '先说结论：听众先知道你要证明什么。',
      '证据具体：用数据、案例或对比支撑判断。',
      '结构清楚：每一页只承担一个推进任务。',
      '行动明确：最后说明下一步谁做什么。',
    ],
    layoutTemplate: 'four_columns',
    deckStyle: 'classic_business',
    contentProfile: 'general',
    archetype: 'summary',
    disciplineStyle: 'general',
    teachingFlow: 'concept_explain',
    visualRole: 'none',
    teachingRole: 'synthesis',
    teachingObjective: '学生能用四个原则检查自己的汇报是否清楚。',
    openingMove: '先给出判断标准，再让学生回头检查自己的页面。',
    concreteAnchor: '结论、证据、结构、行动。',
    studentThinkingMove: '让学生挑一页自己的汇报，判断它缺的是哪一个原则。',
    transferRule: '普通汇报页先看四件事：结论、证据、结构、行动。',
    requiredComponentKinds: [],
    expectedAnchors: ['结论', '证据', '行动'],
  },
  {
    id: 'common_priority_grid',
    label: '通用 2x2',
    description: '测试 2x2 四象限版式：按两个维度组织判断。',
    title: '用 2x2 判断任务优先级',
    outlineDescription: [
      '本页用影响力和紧急度两个维度，把任务分成四类。',
      '学生要看到 2x2 不是装饰，而是把判断标准显式化。',
    ].join('\n'),
    keyPoints: [
      '高影响、高紧急：马上处理，并同步风险。',
      '高影响、低紧急：排进计划，提前准备资源。',
      '低影响、高紧急：快速处理或委托。',
      '低影响、低紧急：延后、合并或取消。',
    ],
    layoutTemplate: 'grid_2x2',
    deckStyle: 'academic',
    contentProfile: 'general',
    archetype: 'concept',
    disciplineStyle: 'general',
    teachingFlow: 'concept_explain',
    visualRole: 'none',
    teachingRole: 'concept_model',
    teachingObjective: '学生能用两个维度解释任务优先级，而不是只凭感觉排序。',
    openingMove: '把优先级从一句主观判断拆成两个维度。',
    concreteAnchor: '影响力 × 紧急度。',
    studentThinkingMove: '让学生把一个任务放进四象限，并说出放置理由。',
    transferRule: '用 2x2 时，先定义两个维度，再解释每个象限该怎么行动。',
    requiredComponentKinds: [],
    expectedAnchors: ['影响力', '紧急度', '委托'],
  },
  {
    id: 'common_problem_rule_image',
    label: '通用双文本图',
    description: '测试左侧上下两块文本、右侧图片：上面讲问题，下面给规则。',
    title: '从问题现象走到判断规则',
    outlineDescription: [
      '本页适合讲“先看现象，再抽规则”的普通教学场景。',
      '左侧上块说明问题现象，下块给出判断规则；右侧用图示把两者连接起来。',
    ].join('\n'),
    keyPoints: [
      '现象：团队反复讨论，但每次都停在个别案例上。',
      '规则：先确认共同模式，再决定是否需要流程、工具或职责调整。',
      '迁移：把零散现象归类，才能形成下次也能用的判断。',
    ],
    layoutTemplate: 'two_text_image',
    deckStyle: 'magazine',
    contentProfile: 'general',
    archetype: 'bridge',
    disciplineStyle: 'general',
    teachingFlow: 'concept_explain',
    visualRole: 'generated_image',
    teachingRole: 'synthesis',
    teachingObjective: '学生能从具体问题抽出可迁移规则。',
    openingMove: '先承认现象，再把现象背后的共同结构找出来。',
    concreteAnchor: '反复讨论个别案例 → 找共同模式 → 定规则。',
    studentThinkingMove: '让学生把一个具体抱怨改写成“现象、模式、规则”三句话。',
    transferRule: '讲问题时先分清现象和规则，再用图把迁移路径画出来。',
    requiredComponentKinds: ['example'],
    expectedAnchors: ['现象', '规则', '共同模式'],
    mediaGenerations: [
      {
        type: 'image',
        elementId: 'gen_img_1',
        aspectRatio: '16:9',
        style: 'clean reasoning diagram',
        prompt:
          'A clean reasoning diagram showing scattered cases grouped into a common pattern, then converted into a reusable rule. Warm editorial classroom style.',
      },
    ],
  },
  {
    id: 'pipeline_tweet_representation',
    label: '流程 + 对照表',
    description: '测试普通课堂最常见的“判断路径 + 证据表”页面。',
    title: DEFAULT_TITLE,
    outlineDescription: DEFAULT_OUTLINE_DESCRIPTION,
    keyPoints: DEFAULT_KEY_POINTS,
    layoutTemplate: 'pipeline_table',
    deckStyle: 'academic',
    contentProfile: 'general',
    archetype: 'concept',
    disciplineStyle: 'code',
    teachingFlow: 'comparison_review',
    visualRole: 'diagram',
    teachingRole: 'comparison',
    teachingObjective:
      '学生能从具体的 list/dict 错误状态看出旧表示守不住对象规则，并理解为什么要把边界集中到 Tweet 类里。',
    openingMove: '从 Tweet() 这个入口追问旧表示守不住哪些对象规则。',
    concreteAnchor: [
      "合法 list: ['David', '2017-09-19', 'Hello, I am so cool', 0]",
      "错误 list: [55, 'Diane', 'Older and even cooler', '2017-09-19']",
      "缺少日期的 dict: {'userid': 'Jacqueline', 'content': 'Has the most dignified cat', 'likes': 12}",
    ].join('\n'),
    studentThinkingMove:
      '先找旧表示仍会接受的错误状态，再判断哪些字段和规则应该集中到 Tweet 类里。',
    transferRule: '写类前先问：对象状态是什么、旧表示守不住什么、类要集中哪些边界。',
    requiredComponentKinds: ['table'],
    expectedAnchors: ['David', 'Diane', 'Jacqueline', 'Tweet()'],
  },
  {
    id: 'visual_three_steps_class_design',
    label: '图示 + 三步',
    description: '测试“解释、图示、三步卡片”的课堂讲授页。',
    title: '写类前的三步判断',
    outlineDescription: [
      '本页把写类前的思考拆成三个判断：先确认对象，再列状态，最后定边界。',
      '学生要看到类不是术语表，而是一套把字段、初始化和操作放在一起维护的设计。',
    ].join('\n'),
    keyPoints: [
      '先问：Tweet 是不是一个需要长期维护状态的对象。',
      '再列状态：userid、created_at、content、likes 必须一起移动。',
      '最后定边界：初始化、读取/修改、点赞操作由 Tweet 集中管理。',
      '用类当蓝图：每个实例按同一结构保存自己的属性值。',
    ],
    layoutTemplate: 'visual_three_steps',
    deckStyle: 'tech_saas',
    contentProfile: 'general',
    archetype: 'concept',
    disciplineStyle: 'code',
    teachingFlow: 'concept_explain',
    visualRole: 'generated_image',
    teachingRole: 'concept_model',
    teachingObjective: '学生能把“写类”转化成对象、状态、边界三个可执行判断。',
    openingMove: '先不写代码，先把 Tweet() 当作一个需要被维护的对象入口。',
    concreteAnchor:
      'Tweet 至少有 userid、created_at、content、likes 四个状态；这些状态不能散落在多个 list、dict 或临时变量里。',
    studentThinkingMove:
      '让学生按“对象是什么、状态有哪些、边界在哪里”的顺序重新组织刚才的失败案例。',
    transferRule: '遇到类设计题，先做三步判断：对象、状态、边界。',
    requiredComponentKinds: ['example'],
    expectedAnchors: ['userid', 'created_at', 'content', 'likes'],
    mediaGenerations: [
      {
        type: 'image',
        elementId: 'gen_img_1',
        aspectRatio: '16:9',
        style: 'clean classroom diagram',
        prompt:
          'A clean lecture slide diagram showing a Tweet object blueprint connected to four fields: userid, created_at, content, likes, then arrows to initialization and allowed operations. Minimal, readable, academic tech style.',
      },
    ],
  },
  {
    id: 'summary_two_by_one',
    label: '两栏 + 总结',
    description: '测试收束页：上方两组要点，底部一句可迁移结论。',
    title: '收束：下次写类前，先问哪三个问题？',
    outlineDescription: [
      '本页收束 Tweet 例子，把旧表示失败和类的职责并排放在一起。',
      '学生最后带走的不是术语，而是下一次写类前可重复使用的检查链。',
    ].join('\n'),
    keyPoints: [
      '旧表示的问题：位置、字段名、缺失字段和非法操作都可能被客户端代码绕过。',
      '类的职责：集中字段名字、初始化逻辑、允许的读写和对象操作。',
      '迁移结论：先问对象，再问旧表示会不会失守，最后再写类。',
    ],
    layoutTemplate: 'two_by_one_summary',
    deckStyle: 'classic_business',
    contentProfile: 'general',
    archetype: 'summary',
    disciplineStyle: 'code',
    teachingFlow: 'comparison_review',
    visualRole: 'none',
    teachingRole: 'synthesis',
    teachingObjective: '学生能把 Tweet 例子的判断顺序迁移到下一道类设计题。',
    openingMove: '回到 Tweet()：这节课最后要留下的是一条写类前的检查链。',
    concreteAnchor: 'list/dict 会接受错误状态；Tweet 类应该集中字段、初始化和操作边界。',
    studentThinkingMove: '让学生把“旧表示失守”和“类集中边界”分别归纳成两组短要点。',
    transferRule: '下次写类前先问：对象是什么、旧表示哪里失守、类要集中什么边界。',
    requiredComponentKinds: [],
    expectedAnchors: ['Tweet()', 'list', 'dict'],
  },
  {
    id: 'three_cards_core_terms',
    label: '三张概念卡',
    description: '测试最普通的概念辨析页：三张卡片并列，不靠长段落。',
    title: '类、实例、属性：先分清三件事',
    outlineDescription: [
      '本页用三张概念卡区分类、实例、属性，帮助学生把后面的 self 和点号访问放到正确位置。',
      '每张卡只讲一个概念，并用 Tweet 的例子落地。',
    ].join('\n'),
    keyPoints: [
      '类：给对象规定字段和操作，是创建 Tweet 对象的蓝图。',
      '实例：按蓝图创建出来的具体对象，例如 t1 这一条推文。',
      '属性：挂在实例上的状态，例如 t1.userid 和 t1.likes。',
    ],
    layoutTemplate: 'three_cards',
    deckStyle: 'magazine',
    contentProfile: 'general',
    archetype: 'definition',
    disciplineStyle: 'code',
    teachingFlow: 'definition_to_example',
    visualRole: 'none',
    teachingRole: 'concept_model',
    teachingObjective: '学生能区分类、实例和属性，并能把 Tweet 例子对应到三者。',
    openingMove: '先把三个词分开，后面看到 self 和点号时就不会混在一起。',
    concreteAnchor: 'Tweet 是类，t1 是实例，t1.userid / t1.likes 是属性。',
    studentThinkingMove: '让学生把每个术语都配一个 Tweet 例子，而不是背定义。',
    transferRule: '读面向对象代码时，先标出类、实例、属性三类东西。',
    requiredComponentKinds: ['example'],
    expectedAnchors: ['Tweet', 't1', 'userid'],
  },
  {
    id: 'text_image_object_blueprint',
    label: '文本 + 图片',
    description: '测试左文右图：一个核心判断配一张对象蓝图。',
    title: '把 Tweet 当作一个要维护的对象',
    outlineDescription: [
      '本页不急着进入代码，而是先把 Tweet 看成一个需要长期维护的对象。',
      '学生要通过右侧对象蓝图看到 userid、created_at、content、likes 不是四个散开的变量，而是同一条推文的状态。',
    ].join('\n'),
    keyPoints: [
      'Tweet 的四个字段描述同一条推文，应该一起保存和移动。',
      '如果字段散落在 list、dict 或临时变量里，客户端代码就容易绕过顺序、类型和缺失字段规则。',
      '类的价值是把字段名字、初始化入口和允许的操作放到同一个对象边界里。',
    ],
    layoutTemplate: 'text_image_split',
    deckStyle: 'academic',
    contentProfile: 'general',
    archetype: 'concept',
    disciplineStyle: 'code',
    teachingFlow: 'concept_explain',
    visualRole: 'generated_image',
    teachingRole: 'concept_model',
    teachingObjective: '学生能把 Tweet 从一组字段提升为一个有状态边界的对象。',
    openingMove: '先看对象蓝图，再问哪些状态必须被同一个对象维护。',
    concreteAnchor: 'Tweet 有 userid、created_at、content、likes 四个字段；它们属于同一条推文。',
    studentThinkingMove: '让学生指出图中的字段为什么不该散落到多个 list、dict 或临时变量里。',
    transferRule: '看到多个字段长期一起出现时，先判断它们是不是同一个对象的状态。',
    requiredComponentKinds: ['example'],
    expectedAnchors: ['Tweet', 'userid', 'likes'],
    mediaGenerations: [
      {
        type: 'image',
        elementId: 'gen_img_1',
        aspectRatio: '16:9',
        style: 'clean academic object diagram',
        prompt:
          'A clean academic diagram of a Tweet object as one container with fields userid, created_at, content, likes connected inside the same boundary. Minimal tech classroom style.',
      },
    ],
  },
  {
    id: 'four_columns_invalid_states',
    label: '四栏并列',
    description: '测试四栏：4 个并列错误状态或检查点。',
    title: '旧表示会放进来的四类错误状态',
    outlineDescription: [
      '本页把 list/dict 旧表示会接受的问题拆成四类并列检查点。',
      '学生要看到这些问题不是语法错误，而是对象规则没有被集中维护。',
    ].join('\n'),
    keyPoints: [
      '顺序错误：list 仍能保存四个值，但位置含义可能全乱。',
      '类型错误：likes、userid、date 的类型可以被客户端随手传错。',
      '字段缺失：dict 少了 created_at 仍可能被传到后续代码。',
      '多余操作：客户端可以直接加无关 key 或绕过点赞规则。',
    ],
    layoutTemplate: 'four_columns',
    deckStyle: 'classic_business',
    contentProfile: 'general',
    archetype: 'concept',
    disciplineStyle: 'code',
    teachingFlow: 'comparison_review',
    visualRole: 'none',
    teachingRole: 'comparison',
    teachingObjective: '学生能把旧表示接受的错误状态分成四类，并说出类要集中哪些边界。',
    openingMove: '把旧表示的失败拆成四类，看它到底守不住哪些规则。',
    concreteAnchor:
      "错误 list: [55, 'Diane', 'Older and even cooler', '2017-09-19']；缺少日期的 dict 仍可能被传来。",
    studentThinkingMove: '让学生把每个错误归到顺序、类型、缺失或越界操作中的一类。',
    transferRule: '评估旧表示时，分别查顺序、类型、缺失字段和越界操作。',
    requiredComponentKinds: ['example'],
    expectedAnchors: ['list', 'dict', 'created_at'],
  },
  {
    id: 'grid_2x2_design_checks',
    label: '2x2 网格',
    description: '测试 2x2 网格：四个设计检查点分组展示。',
    title: '写类前的 2x2 检查',
    outlineDescription: [
      '本页用 2x2 网格组织写类前的四个检查点。',
      '学生要从“数据是否属于同一对象”和“操作是否需要被统一管理”两个方向判断是否该定义类。',
    ].join('\n'),
    keyPoints: [
      '同一对象：userid、created_at、content、likes 是否描述同一条 tweet。',
      '长期状态：这些值是否会在对象生命周期里反复被读取或修改。',
      '统一入口：创建时是否需要统一初始化字段。',
      '统一操作：点赞、读取内容、修改状态是否应该有共同边界。',
    ],
    layoutTemplate: 'grid_2x2',
    deckStyle: 'tech_saas',
    contentProfile: 'general',
    archetype: 'concept',
    disciplineStyle: 'code',
    teachingFlow: 'concept_explain',
    visualRole: 'none',
    teachingRole: 'concept_model',
    teachingObjective: '学生能用四个检查点判断一组数据是否应该收进类里。',
    openingMove: '把“该不该写类”拆成四个检查点，而不是先背定义。',
    concreteAnchor: 'Tweet 的字段一起描述同一条推文，并且点赞、读取和初始化都围绕它发生。',
    studentThinkingMove: '让学生逐格判断 Tweet 是否满足这个检查点，并给出一句理由。',
    transferRule: '写类前用四格检查：同一对象、长期状态、统一入口、统一操作。',
    requiredComponentKinds: ['example'],
    expectedAnchors: ['userid', 'likes', 'Tweet'],
  },
  {
    id: 'two_text_image_problem_rule',
    label: '两块文本 + 图片',
    description: '测试左侧上下两块文本、右侧图片的“问题/规则”讲授页。',
    title: '从旧表示问题走到类的边界',
    outlineDescription: [
      '本页左侧上半块讲旧表示的问题，下半块讲 Tweet 类要集中的规则。',
      '右侧图片把 list/dict 散落字段和 Tweet 对象边界放在一张图里对照。',
    ].join('\n'),
    keyPoints: [
      '问题：list 和 dict 让客户端直接操作字段，顺序、缺失和无关 key 都可能混进来。',
      '规则：Tweet 类把 userid、created_at、content、likes 的初始化和允许操作集中起来。',
      '学生要看清：类不是多写一层包装，而是把对象边界固定下来。',
    ],
    layoutTemplate: 'two_text_image',
    deckStyle: 'academic',
    contentProfile: 'general',
    archetype: 'bridge',
    disciplineStyle: 'code',
    teachingFlow: 'comparison_review',
    visualRole: 'generated_image',
    teachingRole: 'comparison',
    teachingObjective: '学生能从旧表示的问题过渡到类要提供的对象边界。',
    openingMove: '左边先分清问题和规则，右边用对象边界图把两者连起来。',
    concreteAnchor: '旧表示直接暴露字段；Tweet 类集中字段、初始化和点赞操作。',
    studentThinkingMove: '让学生分别指出旧表示放任了什么、类应该收紧什么。',
    transferRule: '从旧表示过渡到类时，先写出“问题”和“规则”两块。',
    requiredComponentKinds: ['example'],
    expectedAnchors: ['list', 'dict', 'Tweet'],
    mediaGenerations: [
      {
        type: 'image',
        elementId: 'gen_img_1',
        aspectRatio: '16:9',
        style: 'clean comparison diagram',
        prompt:
          'A clean classroom comparison diagram: left side scattered list and dict fields, right side a Tweet object boundary containing userid, created_at, content, likes and allowed operations. Minimal academic style.',
      },
    ],
  },
  {
    id: 'code_split_init_trace',
    label: '代码 + 状态追踪',
    description: '测试代码讲解页：左侧代码，右侧追踪 self 和属性变化。',
    title: '从 __init__ 追踪 self 的属性变化',
    outlineDescription: [
      '本页从 __init__ 的真实代码出发，追踪 self 如何接住参数并写入实例属性。',
      '学生要关注当前行读了哪些值、对象内部新增了哪些属性，而不是只看最终答案。',
    ].join('\n'),
    keyPoints: [
      `代码片段：\n${CODE_SPLIT_SNIPPET}`,
      '执行 Tweet(...) 时，Python 创建一个新对象，并把它作为 self 传进 __init__。',
      'who、when、what 是参数；self.userid、self.created_at、self.content、self.likes 是实例属性。',
      '执行结束后，变量 t1 引用这个已经带有四个属性的 Tweet 对象。',
    ],
    layoutTemplate: 'code_split',
    deckStyle: 'tech_saas',
    contentProfile: 'code',
    archetype: 'example',
    disciplineStyle: 'code',
    teachingFlow: 'code_walkthrough',
    visualRole: 'none',
    overflowPolicy: 'preserve_then_paginate',
    preserveFullProblemStatement: true,
    teachingRole: 'state_trace',
    teachingObjective: '学生能按执行顺序解释 self、参数和实例属性之间的关系。',
    openingMove: '从入口 Tweet(...) 开始，不先看结论，只追踪当前行发生了什么。',
    concreteAnchor: CODE_SPLIT_SNIPPET,
    studentThinkingMove: '让学生逐行说出：当前行读了哪个参数，写入了 self 上的哪个属性。',
    transferRule: '追踪 __init__ 时，永远把 self 看成“正在被初始化的那个新对象”。',
    requiredComponentKinds: ['trace'],
    expectedAnchors: ['__init__', 'self.userid', 'Giovanna'],
    workedExampleConfig: {
      kind: 'code',
      role: 'walkthrough',
      exampleId: 'tweet-init-trace',
      codeSnippet: CODE_SPLIT_SNIPPET,
      walkthroughSteps: [
        '创建 Tweet 新对象，并把它绑定到 self。',
        '把 who 写入 self.userid。',
        '把 when 写入 self.created_at。',
        '把 what 写入 self.content，并把 likes 初始化为 0。',
      ],
      finalAnswer: 't1 引用一个已经拥有 userid、created_at、content、likes 的 Tweet 对象。',
    },
  },
];
